### ISSUE TITLE
Problem with ERR STATUS undefined

### ISSUE THREAD

**Issue by markusfigge** [PArns/ioBroker.innogy-smarthome#10]
Guten Morgen,

bin noch neu und versuche mich seit einigen Wochen mit einer Visualisierung. Möchte innogy Smarthome Geräte steuern. Die Darstellung, Auslesen etc. funktioniert einwandfrei, jedoch bekomme ich beim Betätigen eines Schalter/Reglers im Log immer den Fehler ERR STATUS undefined. In der Objektansicht des ioBrokers sehe ich die durch den Schalter/Regler veränderten Werte/Statusinformationen, jedoch rot (statt grün, wie es bei der regulären Web-App der Fall ist) und der Schaltvorgang hat keine Wirkung.

Hier die Fakten:
- raspberry Pi3 (Linux Raspian)
- RWE/Innogy Smarthome Zentrale
- RWE Aktoren: Tür-/Fenster-Sensoren, Heizkörperthermostate, Rauchmelder, Zwischenstecker
- hosts: {
"node": "v4.8.2",
"admin": "version": "2.0.9",
"discovery": "version": "0.4.4",
"web": "version": "2.1.8",
"vis": "version": "1.0.4",
"cloud": "version": "2.0.6",
"tr-064": "version": "0.4.9",
"ping": "version": "1.3.2",
"history": "version": "1.6.3",
"Javascript": "version": "3.4.0",
"mobile": "version": "0.4.11",
"innogy-smarthome": "version": "0.1.17",

Bin am Verzweifeln ... hat jemand eine Idee, was ich falsch mache?

Hier der Link zu meiner Forumsanfrage:
http://forum.iobroker.net/viewtopic.php?f=17&t=8946&p=96186#p96186

**Comment by PArns** [comment]
Hallo Markus, bitte poste einmal die RAW-Daten deiner Geräte (aus der Objektansicht) (vorzugsweise des Zwischensteckers) und verwende bitte entweder dieses Issue oder das Board, aber nicht beides!

**Comment by PArns** [comment]
Nachdem leider keine weiteren Infos hier eingegangen sind, schließe ich dieses Issue
