### ISSUE TITLE
Fehlender WDS Knoten bei einigen Fenstern

### ISSUE THREAD

**Issue by tom3kcgn** [PArns/ioBroker.innogy-smarthome#101]
**Describe the bug**  
In einigen Knotepunkten der Fensterkontakte fehlt der Knoten WDS und damit auch der Status, ob ein Fenster offen oder geschlossen ist.

**To Reproduce**  
Nach einem Neustart des Adapters kann es vorkommen, dass ein anderes Fenster von den Problem betroffen ist, was vor dem Neustart noch den Knoten hatte. 

**Expected behavior**  
Alle Fensterkontakte haben den Knoten WDS und den Status "IsOpen"

**Screenshots & Logfiles**  
![Screenshot 2023-01-08 22 36 26](https://user-images.githubusercontent.com/25109239/211220413-dc3d2746-6b15-4af1-8c1d-5e505e97d10f.png)

**Versions:**  
 - Adapter version: 1.2.1
 - JS-Controller version: 4.0.24
 - Node version: v16.18.1
 - Operating system: Debian GNU/Linux 11 (bullseye)

**Additional context**  
Die IoBroker Instanz läuft als Docker Container. In der alten Version hat dies jedenfalls keine Probleme veruracht.

**Comment by Apollon77** [comment]
Please delete all objects and then restart the adapter. The shown structure seems like the old "pre 1.0" one. And make sure to reload the admin browser window after that first initial start and after all objects were created.

If still an issue please set loglevel to debug and post logfile from Log on disk (/opt/iobroker/log/...) from whole start

**Comment by tom3kcgn** [comment]
> Please delete all objects and then restart the adapter. The shown structure seems like the old "pre 1.0" one. And make sure to reload the admin browser window after that first initial start and after all objects were created.
> 
> If still an issue please set loglevel to debug and post logfile from Log on disk (/opt/iobroker/log/...) from whole start

Just followed your instructions. Deleted the whole Innogy-Objects-Folder, restarted the adapter, refresh browser. But there are still two devices without the WDS Folder.
The logfile you requested: [current-log.log](https://github.com/PArns/ioBroker.innogy-smarthome/files/10372500/current-log.log)

The structure seems to be the same as before:
![image](https://user-images.githubusercontent.com/25109239/211293275-eda47f04-b50d-46e9-950f-d31660532870.png)

**Comment by tom3kcgn** [comment]
Nodes are now available. 
Although the value for "IsReachable" was true and "LowBattery" was false, the contacts were not reachable. After a battery change the contacts were reachable and after deleting the nodes and restarting the adapter the data points were available.

Sorry for the circumstances

**Comment by Apollon77** [comment]
> Although the value for "IsReachable" was true and "LowBattery" was false, the contacts were not reachable.

For this a debug log would have been interesting. Were there messages in Livisi odr were they already deleted/acknowledged? The adapter reads all messages on start and checks for battery/recachability ones and set the states accordingly ... so acknowledging these alerts in Livisi will hide it for the adapter on start ... Could this be?
