### ISSUE TITLE
Innogy Benachrichtigungen als DP Ausgabe?

### ISSUE THREAD

**Issue by JBSullivan** [PArns/ioBroker.innogy-smarthome#102]
Können ggf. auch Nachrichten als Datenpunkt ausgegeben werden?

![image](https://user-images.githubusercontent.com/44617472/211757655-b1e771f7-d6b0-4e5c-8091-cf6035742064.png)

![image](https://user-images.githubusercontent.com/44617472/211758869-aa982114-0512-4f27-8daf-a2838fef8c5e.png)

**Comment by Apollon77** [comment]
Unreachable Nachrichten werden in status changes des "reavhable" states im Devices in den IObjekten umgewandelt. Theoretisch das gleiche bei BatteryLow das hat nur noch keiner getestet.

Ich würde Messages also ggf eher zielgerichtet "übersetzen" also die jetzt anderweitig einzubauen
