### ISSUE TITLE
Target-Temperature.PointTemperature stellt sich wieder zurück

### ISSUE THREAD

**Issue by blumekohl** [PArns/ioBroker.innogy-smarthome#109]
Hallo Zusammen,

ich habe das Problem, dass wenn ich via Node.Red den Status von "innogy-smarthome.0.<ROOM>.<NAME>.Target-Temperature.PointTemperature" ändere sich dieser nach ca. 10-20 Sekunden wieder auf den Wert zurückstellt, welcher zuvor am Thermostat eingestellt ist.

1. Starten des Beispielnodes
![image](https://user-images.githubusercontent.com/129398330/228843263-6cdd1e63-aebf-4caa-8f52-e14974f8d768.png)
2. Überprüfen des Satus im Adapter:
![image](https://user-images.githubusercontent.com/129398330/228843657-2683e6c9-2359-447d-8898-708d0910f57f.png)
3. Warten (10-20 Sekunden)
4. Erneute Prüfung des Status im Adapter:
![image](https://user-images.githubusercontent.com/129398330/228844004-ceade183-50f8-43bb-99a9-6362f50cb8ce.png)

Der Wert sollte sich nicht eigenständig zurückstellen.

Interessant hierbei ist, dass sich der angezeigte Wert am Thermostat selbst nicht ändert (dieser bleibt auf 16,5°C stehen).
Hier scheint der neue Wert (20°C) gar nicht hin übermittelt zu werden.

Ist euch solch ein Verhalten bekannt?

Genutzte Adapter-Version: 1.2.1

**Comment by Apollon77** [comment]
Bite Debug log aktivieren und posten.
Bzw: Wie wird es denn gesetzt? Muss ack=false sein!! Sonst wird der Wert nie rausgesendet. Und nach x Sekunden wird pot. gepollt und so kommt der externe Wert wieder rein.

**Comment by blumekohl** [comment]
> Bite Debug log aktivieren und posten. Bzw: Wie wird es denn gesetzt? Muss ack=false sein!! Sonst wird der Wert nie rausgesendet. Und nach x Sekunden wird pot. gepollt und so kommt der externe Wert wieder rein.

Hallo,
besten Dank, das war die Lösung!
den ack=true/false kann man über das ioBroker Object in Node.Red nicht direkt setzen, es lässt sich allerdings vom Typ "value" (was den Fehler verursachte) auf Typ "command" umstellen, dadurch kann der Wert auch im Thermostat gesetzt werden.

![image](https://user-images.githubusercontent.com/129398330/229082334-4dc69f2e-0771-41c7-bd1e-191b957eb0b1.png)
