### ISSUE TITLE
"Authentication failed"

### ISSUE THREAD

**Issue by Thorben0707** [PArns/ioBroker.innogy-smarthome#11]
Hab iobroker auf dem Raspberry Pi3 laufen, hab den Innogy Adapter installiert und wenn ich jetzt auf "Start authorization" klicken öffnet sich ein kleines pop up wo ich mich mit meinem Innogy Smarthome Name und Passwort anmelde. Dann lädt die seite kurz und zeigt daraufhin dann "Authentication failed"?
Kann mir jemand helfen?

**Comment by PArns** [comment]
Stelle bitte sicher, dass dein Remote Access nicht abgelaufen ist. Dieser ist zwingend nötig!
Und stelle natürlich auch sicher, das dein Passwort korrekt ist

**Comment by Thorben0707** [comment]
Ok den habe ich erst kurz vorher neu gekauft, kann es sein das ich dann neustarten muss oder so?

**Comment by PArns** [comment]
Ich vermute eher, das die Aktivierung ein bisschen dauert... Versuche einfach mal, vom Handy aus (aus dem Mobilfunknetz) Zugriff zu bekommen

**Comment by Thorben0707** [comment]
Remote Zugriff funktioniert ohne Probleme, auch mehrmaliges Neustarten und neuinstallieren des Adapters bringt nichts. Weiterhin "Authentication failed" :(

**Comment by PArns** [comment]
Dann wende dich bitte an den Innogy Support, falls du auch bereits gecheckt hast, ob du Node.JS >= 4 installiert hast

Die Meldung kommt direkt von der API.
Habe auch gerade noch einmal versucht mich bei meinem Adapter anzumelden, keine Probleme.

**Comment by Thorben0707** [comment]
pi@raspberrypi:~ $ nodejs -v
v6.12.2

Ich muss aber sonst im Vorfeld nichts anderes Einstellen oder?
Adapter Installieren, Link klicken, Name und Passwort eingeben - Fertig?

**Comment by Thorben0707** [comment]
Antwort vom Support:
Wir bitten um Ihr Verständnis wenn wir keine Externen nicht SmartHome Geräte supporten.
Falls Sie sich über die normale SmartHome App oder Webseite anmelden können, das Externe Gerät jedoch nicht, so liegt dies außerhalb unseres Supportbereiches. 
Hier wenden Sie sich bitte an den Entwickler der App, welche versucht sich bei uns anzumelden.

**Comment by PArns** [comment]
Sorry, es gibt KEINEN weg von meiner Seite dir zu helfen, da die Meldung eindeutig vom Backend kommt

**Comment by fab242** [comment]
Hallo,
ich habe leider das selbe problem. er versucht immer auf die Seite http://172.17.0.2:3000/authorize?code=87f19a1f2e514cc2852e9a77defa3d42 zu springen. Und da kommt dann "Diese Website ist nicht erreichbar"

**Comment by schotte11** [comment]
Hi

bei mir gehts auch nicht bekomme auch authentication error.  kann von handy mich einloggen (wlan aus)

würde gern von putty installieren aber k.A wie ich das machen kann.  Könnte jemand hilfe geben?

ob Innogy blockt wenn man gebraucht kauft ? hört sich doof an aber vielleicht weil der Box bei jemand anderes angemeldet war und so an den registriert ?????

**Comment by schotte11** [comment]
in log von iobroker steht wie unten - (habe ein neue IP vergeben an Innogy Box while irgendwie ist ein fehler EADDRINUSE in log.  hat aber nichts gebracht.)


host.ioBroker-Pi | 2017-12-30 13:21:33.805 | error | instance system.adapter.innogy-smarthome.0 terminated with code 0 (OK)
-- | -- | -- | --
host.ioBroker-Pi | 2017-12-30 13:21:33.805 | error | Caught by controller[0]: port: 3000 }
host.ioBroker-Pi | 2017-12-30 13:21:33.805 | error | Caught by controller[0]: address: '::',
host.ioBroker-Pi | 2017-12-30 13:21:33.805 | error | Caught by controller[0]: syscall: 'listen',
host.ioBroker-Pi | 2017-12-30 13:21:33.804 | error | Caught by controller[0]: errno: 'EADDRINUSE',
host.ioBroker-Pi | 2017-12-30 13:21:33.804 | error | Caught by controller[0]: code: 'EADDRINUSE',
host.ioBroker-Pi | 2017-12-30 13:21:33.804 | error | Caught by controller[0]: at SmartHome._initialize (/opt/iobroker/node_modules/iobroker.innogy-smarthome/node_modules/innogy-smarthome-lib/lib/smarthome/index.js:308:12)
host.ioBroker-Pi | 2017-12-30 13:21:33.804 | error | Caught by controller[0]: at new Promise (/opt/iobroker/node_modules/iobroker.innogy-smarthome/node_modules/bluebird/js/release/promise.js:79:10)
host.ioBroker-Pi | 2017-12-30 13:21:33.804 | error | Caught by controller[0]: at Promise._resolveFromExecutor (/opt/iobroker/node_modules/iobroker.innogy-smarthome/node_modules/bluebird/js/release/promise.js:483:18)
host.ioBroker-Pi | 2017-12-30 13:21:33.804 | error | Caught by controller[0]: at Promise.cancellationExecute [as _execute] (/opt/iobroker/node_modules/iobroker.innogy-smarthome/node_modules/bluebird/js/release/debuggability.js:324:9)
host.ioBroker-Pi | 2017-12-30 13:21:33.804 | error | Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.innogy-smarthome/node_modules/innogy-smarthome-lib/lib/smarthome/index.js:309:25
host.ioBroker-Pi | 2017-12-30 13:21:33.803 | error | Caught by controller[0]: at Requestor.call (/opt/iobroker/node_modules/iobroker.innogy-smarthome/node_modules/innogy-smarthome-lib/lib/requestor/index.js:42:17)
host.ioBroker-Pi | 2017-12-30 13:21:33.803 | error | Caught by controller[0]: at Requestor.doRequest (/opt/iobroker/node_modules/iobroker.innogy-smarthome/node_modules/innogy-smarthome-lib/lib/requestor/index.js:48:12)
host.ioBroker-Pi | 2017-12-30 13:21:33.803 | error | Caught by controller[0]: at new Promise (/opt/iobroker/node_modules/iobroker.innogy-smarthome/node_modules/bluebird/js/release/promise.js:79:10)
host.ioBroker-Pi | 2017-12-30 13:21:33.803 | error | Caught by controller[0]: at Promise._resolveFromExecutor (/opt/iobroker/node_modules/iobroker.innogy-smarthome/node_modules/bluebird/js/release/promise.js:483:18)
host.ioBroker-Pi | 2017-12-30 13:21:33.803 | error | Caught by controller[0]: at Promise.cancellationExecute [as _execute] (/opt/iobroker/node_modules/iobroker.innogy-smarthome/node_modules/bluebird/js/release/debuggability.js:324:9)
host.ioBroker-Pi | 2017-12-30 13:21:33.803 | error | Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.innogy-smarthome/node_modules/innogy-smarthome-lib/lib/requestor/index.js:49:22
host.ioBroker-Pi | 2017-12-30 13:21:33.802 | error | Caught by controller[0]: at Object.getAuthorizationStatus (/opt/iobroker/node_modules/iobroker.innogy-smarthome/node_modules/innogy-smarthome-lib/lib/oauth2/index.js:171:20)
host.ioBroker-Pi | 2017-12-30 13:21:33.802 | error | Caught by controller[0]: at getAuthorizationStatus (/opt/iobroker/node_modules/iobroker.innogy-smarthome/node_modules/innogy-smarthome-lib/lib/oauth2/index.js:161:13)
host.ioBroker-Pi | 2017-12-30 13:21:33.802 | error | Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.innogy-smarthome/node_modules/innogy-smarthome-lib/lib/requestor/index.js:51:41
host.ioBroker-Pi | 2017-12-30 13:21:33.802 | error | Caught by controller[0]: at Object.startAuthorization (/opt/iobroker/node_modules/iobroker.innogy-smarthome/node_modules/innogy-smarthome-lib/lib/oauth2/index.js:174:20)
host.ioBroker-Pi | 2017-12-30 13:21:33.802 | error | Caught by controller[0]: at startAuthorization (/opt/iobroker/node_modules/iobroker.innogy-smarthome/node_modules/innogy-smarthome-lib/lib/oauth2/index.js:55:26)
host.ioBroker-Pi | 2017-12-30 13:21:33.802 | error | Caught by controller[0]: at EventEmitter.listen (/opt/iobroker/node_modules/iobroker.innogy-smarthome/node_modules/express/lib/application.js:618:24)
host.ioBroker-Pi | 2017-12-30 13:21:33.801 | error | Caught by controller[0]: at Server.listen (net.js:1394:5)
host.ioBroker-Pi | 2017-12-30 13:21:33.801 | error | Caught by controller[0]: at listen (net.js:1298:10)
host.ioBroker-Pi | 2017-12-30 13:21:33.801 | error | Caught by controller[0]: at Server._listen2 (net.js:1262:14)
host.ioBroker-Pi | 2017-12-30 13:21:33.801 | error | Caught by controller[0]: at exports._exceptionWithHostPort (util.js:1043:20)
host.ioBroker-Pi | 2017-12-30 13:21:33.801 | error | Caught by controller[0]: at Object.exports._errnoException (util.js:1020:11)
host.ioBroker-Pi | 2017-12-30 13:21:33.800 | error | Caught by controller[0]: { Error: listen EADDRINUSE :::3000

**Comment by PArns** [comment]
Starte dein Hostsystem noch einmal neu! Der Fehler hat aber nichts mit dem Auth Error zu tun! Bitte daher nicht vermischen. 

An dem "Authentication Failed" kann ich, wie hier noch einmal angemerkt, nichts machen, da der Fehler direkt von der Innogy API kommt

**Comment by Thorben0707** [comment]
Was merkwürdig ist, die Authentifizierung funktioniert mit dem Alexa Skill und auch mit openHAB ohne Probleme, nur beim iobroker adapter kommt ein Error?
  
kann das evt. daran liegen das es eine ältere Zentrale von ehemals RWE ist?
