### ISSUE TITLE
Make adapter ready for Admin v3

### ISSUE THREAD

**Issue by Apollon77** [PArns/ioBroker.innogy-smarthome#14]
For Admin3 some changes are needed: see http://forum.iobroker.net/viewtopic.php?f=24&t=10268

**Comment by PArns** [comment]
Thx for the hint... Those changes are backward compatible with the current admin?

**Comment by Apollon77** [comment]
If unsure ask in Forum please. I think yes because the "new" stuff are "index_m.html" ... so for some time you need to maintain both versions ...
