### ISSUE TITLE
adapter bleibt geld

### ISSUE THREAD

**Issue by eXplOiD1** [PArns/ioBroker.innogy-smarthome#16]
Guten Tag,
gibt es eine debug möglichkeit seit heute morgen bleibt der adapter gelb.

**Comment by eXplOiD1** [comment]
hat sich erledigt aus irgend einem grund hat er offensichtlich den login verloren ich musste mich neu authentifizieren dann gings wieder

**Comment by eXplOiD1** [comment]
ok also irgendwas stimmt nicht das ist jetzt in 3 tagen das 2te mal wo er den login verloren hat,

**Comment by schotte11** [comment]
hat bei mir auch verbindung verloren.  musste erneut password eingeben und dann alles prima wieder.  adaptor versucht zu verbinden, klappt erst wenn ich pass eingegeben hat.

**Comment by eXplOiD1** [comment]
also es sieht so aus als würde der reauth selbstständig nicht funktionieren.

**Comment by PArns** [comment]
Ich habe leider im Moment keine Zeit mir das Problem genauer anzusehen, auch das das Debuggen einer Version mehrere Tage braucht....

Ich kann euch deshalb leider nur um Geduld bitten

**Comment by fab242** [comment]
Hallo, 
Gibt es schon was neues zu dem Problem. Ich muss mich auch jeden Tag neu anmelden.

Gruß
Fabian

**Comment by eXplOiD1** [comment]
es wurde doch schon ein update gebracht seit dem update läuft bei mir alles

**Comment by fab242** [comment]
Oh... das habe ich übersehen. Ich teste es gleich mal

**Comment by PArns** [comment]
Die aktuelle Version 0.2 sollte eigentlich laufen... Zumindest konnte ich bei mir seit gut 1 Woche keinerlei Probleme feststellen (was zugegebenermaßen nix heißen muss ;))
