### ISSUE TITLE
Verzögerungen

### ISSUE THREAD

**Issue by Rainer008** [PArns/ioBroker.innogy-smarthome#17]
Seit dem letzten Update kommt es bei mir immer wieder vor, dass zwischen dem Schalt-Event über ioBroker und der Umsetzung am Heizungskontakt  einige Sekunden bis zu 3 Minuten vergehen.
Auch der umgekehrte Weg, also zwischen Schalten am Thermostat und Anzeige in den Objekten, hat manchmal das gleiche Problem.
Der Wert "innogy-smarthome.0.info.lastRealTimeEventReceived" hat bei mir manchmal ebenfalls eine Differenz zur akt. Uhrzeit von mehreren Minuten.

**Comment by PArns** [comment]
Die Heizkörperthermostate haben ein Update erhalten, welches genau das bewerkstelligen soll. Warum? Das solltet ihr Innogy selbst fragen. Die Verzögerung scheint aber gewollt zu sein. 

Selbiges kann man feststellen, wenn man die Temperatur direkt am Thermostat ändert. Hier dauert es ebenfalls eine gewisse Zeit, bis der Motor entsprechend öffnet oder schließt. Ich vermute, das man hiermit kurze Türöffnungen oder Fensteröffnungen überbrücken möchte
