### ISSUE TITLE
Non customizable port 3000

### ISSUE THREAD

**Issue by peer69** [PArns/ioBroker.innogy-smarthome#18]
If I remember correctly a random port was assigned in earlier versions. Now port 3000 seems to be used which is already bound to grafana in my case. Therefore the adapter won’t start at all. The port assignment should be set back to random at at least be made customizable.

**Comment by PArns** [comment]
Yes, that's true .... Needs some adjustment, but the port was never random

**Comment by peer69** [comment]
Thanks for your reply and your work on this adapter. In terms of the random port I don’t seem to remember correctly. ;) 
Would be great though if the port was made customizable. Currently my solution is to let grafana bind to another port but doing that leads so some trouble of its own so it would be great if i could just bind the adapter to another port.

**Comment by Apollon77** [comment]
Will be configurable in next Update. Already on GitHub - but that version will change object structure!

**Comment by Apollon77** [comment]
Port in 1.0.0 configurable, see https://forum.iobroker.net/topic/61351/livisi-innogy-smarthome-adapter-1-0-0-breaking
