### ISSUE TITLE
Keine Verbindung zu Innogy

### ISSUE THREAD

**Issue by i-am-steve-oh** [PArns/ioBroker.innogy-smarthome#19]
Hi,

ich hab mir dann jetzt auch mal den mobilen Zugang zugelegt. Das Verbindungsfenster wo ich meine Daten eintrage geht nicht zu (wie im Text gefordert) und es gibt auch keine Möglichkeit auf speichern zu drücken.

In der "lib" steht in der "authorization.json" auch ein Oauth Token drin. Der Adapter behauptet aber weiter steif und fest das er nicht verbunden ist.

Vielen Dank für deine Zeit

**Comment by marc-development** [comment]
Hallo,

habe ein identisches Problem.

Nach erfolgter Autorisierung kommt:
"Login complete! You can now close this window and the settings!"

Instanz bleibt aber "gelb"
Im Log:
Adapter is not connected ... Will recheck in 30 seconds!
Adapter is still not connected to the Innogy API, restarting!

Im Dateisystem wird eine aktuelle Datei abgelegt:
/opt/iobroker/node_modules/innogy-smarthome-lib/data/auth/authorization.json

Nach der Autorisierung bleiben die Knöpfe für "Speichern" und "Speichern und Schliessen" grau.
Die Einstellungen können nur normal geschlossen werden.

Getestet mit Win 10 - Edge / IE 11 / Firefox 61.0 und Ipad mit Safari

Admin Version 3.4.6
Adapter Version: 0.2.0

**Comment by DeepSpace7** [comment]
Hallo,
ich habe leider auch das selbe Problem:
Es kommt nach der Autentifizierung die Meldung "Login complete! You can now close this window and the settings!", aber auf den iobroker Fenster tut sich nichts und die Instanz bleibt auf gelb. #21

**Comment by Gerrett84** [comment]
Hallo,

Habe das selbe Problem, Trost Meldung "Login complete [..]" Tut sich im iobroker Adapter nichts . 
Hab das ganze auf verschrieben Browsern und Geräten getestet, überall das selbe Problem. 

Gibt es zu diesem Probleme Neuigkeiten? Ich wollte gerne von OH2 auf iobroker umsteigen, aber ohne ein laufenden Innogy Apdater wäre das schwierig :-/

**Comment by PArns** [comment]
Das Problem sollte mittlerweile behoben sein! Falls nicht, bitte ein neues issue öffnen
