### ISSUE TITLE
A little bit docu will not harm :)

### ISSUE THREAD

**Issue by GermanBluefox** [PArns/ioBroker.innogy-smarthome#2]
What do I need to use this adapter? Must I configure something? And so on.

**Comment by PArns** [comment]
You mean some kind of Wiki? :p
I'll add it as soon as the adapter runs stable here ...

But there is nothing much to configure! Install the adapter, open the admin and link it to your account ... That's it!

**Comment by GermanBluefox** [comment]
At least for what is that.?

> This adapter is used to connect the innogy smarthome devices to ioBroker. You can read more about innogy [here](https://www.innogy.com).

**Comment by PArns** [comment]
Added
