### ISSUE TITLE
Error: Adapter is not configured or needs reauthorization!

### ISSUE THREAD

**Issue by SHSolution** [PArns/ioBroker.innogy-smarthome#23]
Hi,

I'm trying to connect my innogy adapter. After entering my credentials in the auth popup I receive the message:

`"Login complete! You can now close this window and the settings!"`

Sometimes I get a message like: <ip-address>:3000 unable to connect.

Although I get Login complete message the adapter does not got online and logs the following warnings:

> Adapter is not configured or needs reauthorization! Please go to the adapter settings and start the authorization

Adapter Version is: 0.2.0

Any hints?

Thanks and regards.

**Comment by eXplOiD1** [comment]
selbes Problem hier
beim ersten mal hat er es gemacht bei jedem weiteren versuch kommt. 

Die Website ist nicht erreichbar 192.168.3.106 hat die Verbindung abgelehnt.
Auf Google nach 192 168 106 3000 authorize suchen
ERR_CONNECTION_REFUSED

**Comment by Apollon77** [comment]
Plesse check 1.0.0 https://forum.iobroker.net/topic/61351/livisi-innogy-smarthome-adapter-1-0-0-breaking

Reopen or open a new issue with details.
