### ISSUE TITLE
Batterie Zustände nicht vorhanden

### ISSUE THREAD

**Issue by JBSullivan** [PArns/ioBroker.innogy-smarthome#24]
Sorry ich bin neu bei GitHub und weiß nicht ob das hier an der richtigen Stelle platziert ist.

Ich kann in iobroker die Zustände der Batterien von den einzelnen Aktoren nicht sehen. Ist das evtl. noch gar nicht parametriert oder ein Bug?

**Comment by JBSullivan** [comment]
Ich habe heute das erste mal eine Batteriewarnung als Nachricht ins Innogy System bekommen. Kann man ggf. die Mitteilungen (Nachrichten) als Datenpunkt ausgeben. Offensichtlich werden alle Batterie Warnungen nur als Nachrichten ausgegeben.

**Comment by PArns** [comment]
Das Nachrichtensystem ist in der Tat derzeit nicht implementiert. Eigentliche Batteriezustände gibt es, meines Wissens nach, leider gar nicht ... Werde aber noch mal in die Doku schauen, welche seit ein paar Wochen nun auch öffentlich zur Verfügung steht

**Comment by JBSullivan** [comment]
> Das Nachrichtensystem ist in der Tat derzeit nicht implementiert. Eigentliche Batteriezustände gibt es, meines Wissens nach, leider gar nicht ... Werde aber noch mal in die Doku schauen, welche seit ein paar Wochen nun auch öffentlich zur Verfügung steht

Irgend etwas in Richtung Batterie Meldungen muss es geben, denn ich habe in OpenHab so etwas gelesen, das der dortige Innogy Binding jetzt über eine "bereinigte" Batterie Meldung verfügt.

**Comment by PArns** [comment]
Wenn du Zeit und Lust hast, kannst du das gerne contributen! Ich gehe aber davon aus, das die Jungs die Sachen manuell nach der Meldung filtern

**Comment by Apollon77** [comment]
Will be added in next version (theortically ... i never saw them ... so we need to maybe check after update)

**Comment by Apollon77** [comment]
Ok wir konnten isReachable gestern testen ... lowBattery SOLLTE genauso tun, ist aber nicht getestet bisher.

Zu testen wäre:
1.) Wenn ein Gerät aktuell eine "low Battery" message hat und der Adapter startet dann sollte bei dem Gerät der LowBattery tate auf true sein, lle anderen auf false
2.) Wenn sich zur Adapter Laufzeit der Status ändert bzw die Message gelöscht wird (manuell oder weil Batterie getauscht wurde) dann sollte sich der Status im Device on the fly ändern - gleiches Falls während der Laufzeit ein Gerät in "Low Batters" geht

Wenn das jemand testen kann viel spass - ich nehme gern ein Debug Log (inkl. dem aktivierten "debug-setting" in der konfig!)

**Comment by Apollon77** [comment]
see also https://forum.iobroker.net/topic/61351/livisi-innogy-smarthome-adapter-1-0-0-breaking
