### ISSUE TITLE
Problems with Authentification since last update

### ISSUE THREAD

**Issue by viper-sg2** [PArns/ioBroker.innogy-smarthome#25]
When i would like to connect to the innogy api i will get this message in the iobroker logs: "You do not have mobile access for the logged in Innogy account! Please purchase mobile access or move ioBroker to the same subnet as the SHC"

I use iogroger as a docker container in bridge mode on my local NAS. I installed the last update of this adapter.

**Comment by PArns** [comment]
Problem should be solved with changes on Innogy API side
