### ISSUE TITLE
Zustände Aktivieren

### ISSUE THREAD

**Issue by eXplOiD1** [PArns/ioBroker.innogy-smarthome#30]
Guten Abend,
Wird es in einer zukünftigen version möglich sein zustände zu aktivieren / deaktivieren?

MfG
eXplOiD

**Comment by PArns** [comment]
Sorry für den Delay, das sollte bereits immer schon möglich sein!

**Comment by eXplOiD1** [comment]
ok das Problem ist es das mir die in innogy angelegten zustände nicht angezeigt werden

**Comment by PArns** [comment]
Aktualisiere mal auf 0.3.0 und schaue, ob das Problem immer noch besteht

**Comment by eXplOiD1** [comment]
mir wird nur 0.2.11 angezeigt

**Comment by eXplOiD1** [comment]
Adapter    "innogy-smarthome": 0.2.11  , installed 0.2.11
das sagt er mir bei update

**Comment by eXplOiD1** [comment]
habs jetzt über umwege drauf bekommen mit der 0.3 gehts danke

**Comment by PArns** [comment]
0.3.0 ist derzeit nur auf GIT verfügbar, da diese die neue Innogy API implementiert, die ab nächsten Monat zwingend erforderlich wird (jetzt schon erforderlich für die 2.0 Zentrale ist).
Das Update werde ich zur Verfügung stellen, sobald es sich als Stabil heraus gestellt hat.

Danke für das Update
