### ISSUE TITLE
Seit v3.0 bekomme ich Unknown State meldungen

### ISSUE THREAD

**Issue by eXplOiD1** [PArns/ioBroker.innogy-smarthome#31]
innogy-smarthome.0 | 2019-04-30 11:50:54.693 | warn | Unknown state (please report to dev):shutterLevel {"name":"shutterLevel","lastchanged":"2019-04-10T15:14:08.437Z"}
-- | -- | -- | --
innogy-smarthome.0 | 2019-04-30 11:50:54.673 | warn | Unknown state (please report to dev):isSmokeAlarm {"name":"isSmokeAlarm","value":false,"lastchanged":"2019-04-10T15:14:09.105Z"}
innogy-smarthome.0 | 2019-04-30 11:50:54.671 | warn | Unknown state (please report to dev):isSmokeAlarm {"name":"isSmokeAlarm","value":false,"lastchanged":"2019-04-10T15:14:07.540Z"}
innogy-smarthome.0 | 2019-04-30 11:50:54.666 | warn | Unknown state (please report to dev):remainingQuota {"name":"remainingQuota","value":0,"lastchanged":"2019-04-10T15:13:59.933Z"}

**Comment by Apollon77** [comment]
Already implemented
