### ISSUE TITLE
Try to set state. Acknowledged false

### ISSUE THREAD

**Issue by jensfr1** [PArns/ioBroker.innogy-smarthome#32]
Hello, 
I am trying to update a state in the objects overview e.g. setting temperature and always getting Acknowledged: FALSE. 
Adapter is running green. Any idea @PArns how to fix it? 

Thanks, Jens

**Comment by winni-priel** [comment]
Bei mir das gleiche, Werte lassen sich nicht ändern. Auch anderes z.B.  dimlevel lässt sich nicht ändern. Adapter 0.32.

**Comment by PArns** [comment]
Bitte installiert Version 0.3.3, das Problem sollte mit dieser Version endlich behoben sein!
