### ISSUE TITLE
Keine Schimmelwarnung in ioB

### ISSUE THREAD

**Issue by JBSullivan** [PArns/ioBroker.innogy-smarthome#34]
In ioB wird das Flag für Schimmelwarnung nicht von False auf True gesetzt obwohl dieses in der innogy Basis (V1) für den entsprechenden Raum als Meldung ausgegeben wird.
![2019-05-18 08_11_10-SmartHome](https://user-images.githubusercontent.com/44617472/57965450-c4eb4200-7944-11e9-934c-1c6ffabcabd1.png)
![2019-05-18 08_29_41-objects - ioBroker](https://user-images.githubusercontent.com/44617472/57965645-2d3b2300-7947-11e9-9f84-36988ba57c68.png)

**Comment by Apollon77** [comment]
Debug log bitte liefern für so einen Fall ...

**Comment by Apollon77** [comment]
provide details based on 1.0.0 if needed and check again ... Reopen f it is still relevant, see https://forum.iobroker.net/topic/61351/livisi-innogy-smarthome-adapter-1-0-0-breaking
