### ISSUE TITLE
Start authorization geht nicht mehr Adapter gelb

### ISSUE THREAD

**Issue by Heyjo69** [PArns/ioBroker.innogy-smarthome#38]
Hallo, nach dem Start authorization kommt immer diese Fehlermeldung
{"code":"EAI_AGAIN","errno":"EAI_AGAIN","syscall":"getaddrinfo","hostname":"api.services-smarthome.de","host":"api.services-smarthome.de","port":443}
Woran kann das liegen. Gestern war noch alles OK
Vielen Danke schon mal und viele Grüße

**Comment by PArns** [comment]
Das sollte in der regel an einem API problem liegen, Innogy/Livisi hat derzeit leider einige API Probleme
