### ISSUE TITLE
Alarmsirene Auslösung

### ISSUE THREAD

**Issue by JBSullivan** [PArns/ioBroker.innogy-smarthome#39]
Für die Innensirene steht kein Status zum manuellen Auslösen der Sirene zur Verfügung. In der Innogy App kann man die Sirene aber zu Testzwecken auslösen. Ist es möglich die Funktion auch via ioB zur Verfügung zu stellen? Diese Funktion wäre Interessant wenn man z.B. andere SmartHome Komponeten als Innogy Geräte / Zustände für Schaltbedingung in die Alarmkette mit einbauen möchte.

Das gleiche gilt für die drei Soundtypen (Alarm, Rückmeldung, Benachrichtigung). Auch hier kann man in der Innogy App verschiedene Töne auswählen und "Probe hören".

Im Adapter gibt es aber nur die beiden Datenpunkte "ActivChanel & IsOn"  Gibt es eine Chance den Sirenen Datenpunkt noch ein weniger attraktiver zu gestalten?

**Comment by Apollon77** [comment]
Is this still relevant?

**Comment by JBSullivan** [comment]
Sorry, heute erst gelesen - JA ist noch aktuell, es sei denn deine Änderungen der letzten Tage haben dieses Problem ebenfalls mit beseitigt.
Ich muss unbedingt mein Testsystem aktivieren. Vielleicht finde ich zwischen den Feiertagen Zeit hier auch ein wenig unterstützend tätig zu werden.

**Comment by Apollon77** [comment]
Da ich nicht weiss wie das aussheit mpsste man nach details im Livisi Forum fragen ... Dazu brauche ich mehr details

**Comment by JBSullivan** [comment]
So sieht das ganze in der Zentrale (1. Screenshot) und im Smarthome Explorer (Screenshot 2+3) aus. Welche API Adresse aber diesen Trigger ggf. auslöst, weiß ich auch nicht.

Der Smarthome Explorer wurde in übrigen von dem  EX Innogy/livisi Mitarbeiter msagner programmiert und der Allgemeinheit vor Jahren zur Verfügung gestellt. Leider holt der Smarthome Explorer die Daten auch nur aus der Cloud ab und funktioniert nicht mit dem Zugang zur lokalen Zentrale. Wenn du @Apollon77  von den Livisi ggf. einen Entwickler Account auf einen offene Zentrale zur Verfügung gestellt bekommen haben solltest, kann ich dir die Installationsdatei des Smarthome Explorer gerne zukommen lassen.


Ein Aufruf an msagner im Livisi Forum blieb bislang ungehört, sodaß ich da wenig Chancen sehe dieses Tool über das Q1-2023 weiter nutzen zu können.

https://community.livisi.de/forum/thread/4806-lokaler-zugriff-mit-smarthome-commander/?postID=39919#post39919

![image](https://user-images.githubusercontent.com/44617472/209466315-88181fff-847d-4dc9-9a86-f03eb486d98a.png)


![image](https://user-images.githubusercontent.com/44617472/209466272-ee351587-9213-4b61-993b-14c73eb8da2d.png)

![image](https://user-images.githubusercontent.com/44617472/209469430-9d5cf042-226a-4b8f-9f54-a84cefea44a6.png)

**Comment by Apollon77** [comment]
Ist das denn im Adapter sichtbar?bzw schick doch mal bitte die device Lotterielos aus dem debug log von dem Gerät. Aber fragender ja was man senden muss um es zu steuern. Mit dem device json kann ich mal fragen.

**Comment by JBSullivan** [comment]
![image](https://user-images.githubusercontent.com/44617472/209469584-94cb0396-1c59-47cd-9329-bd3fa50cb083.png)

Es kommt nochmal eine Zwischenabfrage bevor die Sirene wirklich loslegt.

![image](https://user-images.githubusercontent.com/44617472/209469708-cf37b6a4-aa6c-4b61-8c86-0c8776a1247b.png)

Auch wenn man die Sirene händisch über die Livisi Zentrale einschaltet, ändert sich an den Objekt States nichts :( Das einzige was sich ändert ist, das dass value im Activ Chanel von "none" auf "Alarm" geht. Wie man das aber von extern triggern kann - ???

![image](https://user-images.githubusercontent.com/44617472/209469768-fa8bfc61-0b6e-4ca0-b495-2faf56fc30f2.png)

![image](https://user-images.githubusercontent.com/44617472/209469750-4ca76be1-b88d-41fb-969c-9d6346f71054.png)

**Comment by Apollon77** [comment]
Frage an Livisi Entwickler-Forum gestellt

**Comment by Apollon77** [comment]
@JBSullivan Bitte GitHub version versuchen ... ActiveState sollte nun schreibbar sein und damit steuerbar

**Comment by JBSullivan** [comment]
Habe eben die GIT Version installiert - an welcher Stelle konkret sollte die Änderung wirksam sein? Direkt unter der Alarmsirene im ActiveChannel geht es nicht. Da ist kein Switch der via True/False die Sirene auslösen könnte.

![image](https://user-images.githubusercontent.com/44617472/210594813-e9085fff-d3a0-48b8-93db-49caa9faa534.png)


Ich habe daraufhin mal in der Zentrale einen neuen Zustand (Virtuelle Trigger) angelegt, der die Alarmsirene auslöst. Der Datenpunkt läßt sich als Switch mit True/False schalten. Es geht also im Prinzip auf diesem Wege. Das Gerät direkt antriggern geht aber nicht (siehe oben)

![image](https://user-images.githubusercontent.com/44617472/210594465-07ca406d-1351-40b1-8399-507fba099937.png)

**Comment by Apollon77** [comment]
DUmiusst "ActiveChannel" auf "Alarm" setzen als Wert, dann sollte es auslösen. Zum aus machen wieder auf "None"

**Comment by JBSullivan** [comment]
AHH - OK - funktioniert perfekt 👍👍👍

**Comment by Apollon77** [comment]
Da ich nicht weiss was bei "activeChannel" vllt noch für Werte existieren wollte ich da gerade nicht eine Harte liste hinterlegen. Release kommt
