### ISSUE TITLE
Add Discovery Support for this Adapter

### ISSUE THREAD

**Issue by Apollon77** [PArns/ioBroker.innogy-smarthome#4]
Hey,

please check out the Discovery-Adapter (https://github.com/ioBroker/ioBroker.discovery) and check if the device can be detected somehow (special url with defined answer, special port, upnp, udp or other technologies?!). If yes it would great if you could add a pull request to the Discovery-Adapter with the needed code.
Support needed? Contact me (Apollon77) in Forum as forum thread or PN ;-)

Ingo

**Comment by PArns** [comment]
Hell Ingo, Innogy offers no direct API Access, therefore you can't discover the SHC/Hub. It's completely inaccessable on the local LAN.

I've asked the guys from Innogy a lot of times how and when there'll be a version with direct access. With the current SHC they won't offer such a feature. Therefore autodetect isn't possible, sorry :(

**Comment by Apollon77** [comment]
Thank you for checking, then it's ok :-(
