### ISSUE TITLE
Type z.B. Shutter.Level (Rolladenschalter) falsch und lässt sich daher nicht ansteuern

### ISSUE THREAD

**Issue by gizmoooo512** [PArns/ioBroker.innogy-smarthome#42]
Bekomme beim Starten der Instanz (ab Version 0.3.0 bis 0.3.4) folgenden Fehler im Log:

innogy-smarthome.0 | 2020-02-01 12:52:22.078 | warn | (17725) Unknown state (please report to dev):shutterLevel {"name":"shutterLevel","value":100,"lastchanged":"2020-02-01T07:03:52.929Z"}
-- | -- | -- | --
innogy-smarthome.0 | 2020-02-01 12:52:22.073 | warn | (17725) Unknown state (please report to dev):shutterLevel {"name":"shutterLevel","value":100,"lastchanged":"2020-02-01T07:03:53.728Z"}
innogy-smarthome.0 | 2020-02-01 12:52:22.069 | warn | (17725) Unknown state (please report to dev):isSmokeAlarm {"name":"isSmokeAlarm","value":false,"lastchanged":"2020-01-23T02:34:35.695Z"}

Versuche ich nun den Wert Shutter.Level zu überschreiben bekomme passiert nichts.
Bei den Objekten habe ich gesehen, dass z.B. Type beim Shutter.Level auf String gesetzt ist. Überschreibe ich den Wert zu Number funktioniert das Ansprechen des Shutter.Level korrekt und ich kann die Rolladen ansteuern. 
Eine Idee, wie das korrigiert werden kann (speichern den Type hält dies nur bis zum nächsten Neustart der Instanz).

Danke!

**Comment by uboot21** [comment]
Schau hier wurde es bereits gelöst, funktioniert prima bei mir 
https://github.com/PArns/ioBroker.innogy-smarthome/pull/40/files

**Comment by PArns** [comment]
Sollte nun auch mit 0.3.6 direkt funktionieren
