### ISSUE TITLE
Update stable version in repo to 0.3.4

### ISSUE THREAD

**Issue by GermanBluefox** [PArns/ioBroker.innogy-smarthome#45]
# Think about update stable version to 0.3.4
**Version**: stable=**0.3.3** (160 days old) => latest=**0.3.4** (47 days old)
**Installs**: stable=**246** (60%), latest=**81** (19.76%), total=**410**
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L524)

**Comment by PArns** [comment]
Done
