### ISSUE TITLE
Stabilitätsprobleme seit letztem Firmware Update

### ISSUE THREAD

**Issue by JBSullivan** [PArns/ioBroker.innogy-smarthome#46]
Es gibt seit dem letzten Update der Zentrale V1.0 Stabilitätsprobleme mit dem Adapter -> siehe:

https://forum.iobroker.net/topic/26064/innogy-adapter-bitte-dringend-aktualisieren/4

**Comment by PArns** [comment]
Der beschriebene Cert-Fehler sollte mittlerweile behoben sein
