### ISSUE TITLE
Zertifikatsfehler beim Start authorization

### ISSUE THREAD

**Issue by Rockid999** [PArns/ioBroker.innogy-smarthome#47]
Erstmal vielen Dank für die tolle Arbeit.
Habe den Adapter in der Vergangenheit schon in alter Version erfolgreich genutzt und wollte die aktuelle Corona Zeit nutzen um einen neuen Raspberry aufzusetzen.
Bekomme allerdings beim Start authorization die Fehlermeldung:
SSL_ERROR_BAD_CERT_DOMAIN
Ist da vllt ne Domäne umgezogen oder etwas in der Art?
Danke und Grüße,
Frank

![grafik](https://user-images.githubusercontent.com/62594002/77410855-df3f4900-6dbb-11ea-8a32-e04839863b0e.png)

**Comment by PArns** [comment]
Danke für die Meldung, ist mittlerweile behoben!
Das Problem trat kurzfristig nach einem Providerwechsel meiner Domain auf. Sorry!
