### ISSUE TITLE
update stable repo?

### ISSUE THREAD

**Issue by Apollon77** [PArns/ioBroker.innogy-smarthome#5]
Hey,

Stable Repo still has v0.1.13. When still the most stable version, everything great, if not please update in stable-repo.

(see https://github.com/ioBroker/ioBroker.repositories)

Thanx for checking

Ingo F

**Comment by PArns** [comment]
Hey Ingo, Bluefox has to do so, sorry :( 
I can create a branch and a pull request, but I don't know if this is the way to do it ;)

There are also currently some ongoing discussions with Innogy, as there is a socket bug which I need to fix first. But as I'm currently out of office, I'll need a few more days to have a look at it

Patrick

**Comment by Apollon77** [comment]
Only wanted to trigger and make you think :-)

process for stable-repo-updates is: fork repo-project, update version in stable and send in pull-request, so you as developer has the full power :-)

**Comment by PArns** [comment]
kk, thx for the clarification ;)

I'll do so within the next days

**Comment by PArns** [comment]
Done
