### ISSUE TITLE
Trotz neuen Adapter 0.3.6 bekomme ich einfach keine erfolgreiche Autorisierung.

### ISSUE THREAD

**Issue by Lorilatschki** [PArns/ioBroker.innogy-smarthome#51]
IoBroker  js-controller 3.1.6 mit ioBroker.admin 4.1.1 im Docker Container in einer Synology DNS 218+.
Nach dem ich meine Zugangsdaten eingegeben habe, warte ich ca. 20 Sekunden danach bekomme ich immer Die Website ist nicht erreichbar. 
Witzig ist das in der Request URL der code sogar der API Code als Antwort kommt: http://172.17.0.3:3000/authorize?code=**ae0fe200bd9445b386a18e.......**
Der Port 3000 ist im Container und in der Fritzbox freigegeben bzw. weitergeleitet. Was kann ich denn noch machen bzw. irgendwelche Log Ausgaben die irgendwo versteckt sind die weiterhelfen?

**Comment by Lorilatschki** [comment]
Das Problem tritt in einem IoBroker in Windows **nicht** auf! Daher hat es mit Docker und sehr wahrscheinlich einem fehlenden offnen Port zu tun.

**Comment by Mark-Greek** [comment]
1. Bei dein Router z.B. Fritzbox brauchst du keine Portfreigabe machen

2. Bei dein Docker oder Portainer GUI -> ioBroker Container den TCP Port 3000 weiterleiten auf 3000 ( aufpassen wenn du ein anderen Container hast, der diesen Port nutzt kurz stoppen )

3. Authentifizierung durch laufen bis die Fehlermeldung kommt " Die Website ist nicht erreichbar" usw...

den link kopieren z.B.  
http://172.17.0.3:3000/authorize?code=ae0fe200bd9445b386a18e......................

und einfach die IP Adresse des iobrokers einfügen z.B. 

http://192.168.178.253:3000/authorize?code=ae0fe200bd9445b386a18e......................

auf eine neues Fenster des Browsers rein und Enter ;)


@PArns wenn du willst kannst du diese Info bei deine Readme einfügen. Für User die mit ein Docker unter Raspberry arbeiten sehr interessant. Ich habe diesen Trick nach zwei Nächte gefunden :)

**Comment by Lorilatschki** [comment]
Hat bei mir auch funkioniert. Das Problem ist das er die IP vom Bridge vom Container nimmt. Am besten wäre es wenn man im Adapter die Resonse IP ändern könnte, dann würde es "automatisch" gehen.
