### ISSUE TITLE
Falsches state aufgrund Update js-controller / Admin 5.x.x

### ISSUE THREAD

**Issue by JBSullivan** [PArns/ioBroker.innogy-smarthome#55]
Wäre toll wenn das gefixt werden könnte. Ursache hängt mit der Umstellung auf den Admin 5.x.x. zusammen (sieh Forum)

`
<html>
<body>

innogy-smarthome.0 | 2021-05-11 10:35:00.745 | warn | (1232) Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
innogy-smarthome.0 | 2021-05-11 10:35:00.744 | info | (1232) terminating
innogy-smarthome.0 | 2021-05-11 10:35:00.736 | error | (1232) this._uninitialize is not a function
innogy-smarthome.0 | 2021-05-11 10:35:00.736 | error | (1232) TypeError: this._uninitialize is not a function at SmartHome.finalize (C:\iobroker\GLT\node_modules\innogy-smarthome-lib\lib\smarthome\index.js:112:17) at SmartHome._errorHandler (C:\io
innogy-smarthome.0 | 2021-05-11 10:35:00.735 | error | (1232) unhandled promise rejection: this._uninitialize is not a function
innogy-smarthome.0 | 2021-05-11 10:35:00.734 | error | (1232) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
innogy-smarthome.0 | 2021-05-11 10:33:43.180 | info | (1232) State value to set for "innogy-smarthome.0.Garten.Wall-E.ChargingCurrent" has to be type "string" but received type "number"
innogy-smarthome.0 | 2021-05-11 10:33:43.179 | info | (1232) State value to set for "innogy-smarthome.0.Garten.Wall-E.ChargingCycles" has to be type "string" but received type "number"
innogy-smarthome.0 | 2021-05-11 10:33:43.179 | info | (1232) State value to set for "innogy-smarthome.0.Garten.Wall-E.BatteryLevel" has to be type "string" but received type "number"
innogy-smarthome.0 | 2021-05-11 10:33:43.178 | info | (1232) State value to set for "innogy-smarthome.0.Garten.Wall-E.OperationTimeBlade" has to be type "string" but received type "number"
innogy-smarthome.0 | 2021-05-11 10:33:43.177 | info | (1232) State value to set for "innogy-smarthome.0.Garten.Wall-E.OperationTimeWR" has to be type "string" but received type "number"
innogy-smarthome.0 | 2021-05-11 10:33:43.176 | info | (1232) State value to set for "innogy-smarthome.0.Garten.Wall-E.OperationTimeWL" has to be type "string" but received type "number"
innogy-smarthome.0 | 2021-05-11 10:33:43.176 | info | (1232) State value to set for "innogy-smarthome.0.Garten.Wall-E.BladeServiceTime" has to be type "string" but received type "number"
innogy-smarthome.0 | 2021-05-11 10:33:43.175 | info | (1232) State value to set for "innogy-smarthome.0.Garten.Wall-E.TotalMowingTime" has to be type "string" but received type "number"
innogy-smarthome.0 | 2021-05-11 10:33:43.174 | info | (1232) State value to set for "innogy-smarthome.0.Garten.Wall-E.MowingCycles" has to be type "string" but received type "number"
innogy-smarthome.0 | 2021-05-11 10:33:43.173 | info | (1232) State value to set for "innogy-smarthome.0.Garten.Wall-E.OperatingTime" has to be type "string" but received type "number"
innogy-smarthome.0 | 2021-05-11 10:33:43.172 | info | (1232) State value to set for "innogy-smarthome.0.Garten.Wall-E.TiltSlope" has to be type "string" but received type "number"
innogy-smarthome.0 | 2021-05-11 10:33:43.171 | info | (1232) State value to set for "innogy-smarthome.0.Garten.Wall-E.RemainingOperationTime" has to be type "string" but received type "number"
innogy-smarthome.0 | 2021-05-11 10:33:43.171 | info | (1232) State value to set for "innogy-smarthome.0.Garten.Wall-E.NextOperationStartTime" has to be type "string" but received type "number"
innogy-smarthome.0 | 2021-05-11 10:33:43.170 | info | (1232) State value to set for "innogy-smarthome.0.Garten.Wall-E.RainDelay" has to be type "string" but received type "number"
innogy-smarthome.0 | 2021-05-11 10:33:43.168 | info | (1232) State value to set for "innogy-smarthome.0.Garten.Wall-E.RainSensor" has to be type "string" but received type "boolean"
innogy-smarthome.0 | 2021-05-11 10:33:43.167 | info | (1232) State value to set for "innogy-smarthome.0.Flur.Rauchmelder-Flur-OG.IsSmokeAlarm" has to be type "string" but received type "boolean"
innogy-smarthome.0 | 2021-05-11 10:33:43.166 | info | (1232) State value to set for "innogy-smarthome.0.Kinderzimmer-OG.Rauchmelder.IsSmokeAlarm" has to be type "string" but received type "boolean"
innogy-smarthome.0 | 2021-05-11 10:33:43.165 | info | (1232) State value to set for "innogy-smarthome.0.Keller.Rauchmelder-Speicher.IsSmokeAlarm" has to be type "string" but received type "boolean"
innogy-smarthome.0 | 2021-05-11 10:33:43.150 | info | (1232) State value to set for "innogy-smarthome.0.Ankleidezimmer.Rauchmelder.IsSmokeAlarm" has to be type "string" but received type "boolean"
innogy-smarthome.0 | 2021-05-11 10:33:43.149 | info | (1232) State value to set for "innogy-smarthome.0.Flur.Rauchmelder-Flur.IsSmokeAlarm" has to be type "string" but received type "boolean"
innogy-smarthome.0 | 2021-05-11 10:33:43.147 | info | (1232) State value to set for "innogy-smarthome.0.Variable.HTTP-Anfrage.IsSending" has to be type "string" but received type "boolean"
innogy-smarthome.0 | 2021-05-11 10:33:43.145 | info | (1232) State value to set for "innogy-smarthome.0.Garten.Alarmsirene.IsOn" has to be type "string" but received type "boolean"
innogy-smarthome.0 | 2021-05-11 10:33:42.788 | warn | (1232) Unknown state (please report to dev):errorDescription {"name":"errorDescription","value":"CN999;ISSUE;UNKNOWN","lastchanged":"2021-05-10T18:00:14.055Z"}
innogy-smarthome.0 | 2021-05-11 10:33:42.787 | warn | (1232) Unknown state (please report to dev):chargingCurrent {"name":"chargingCurrent","value":1500,"lastchanged":"2021-05-10T18:00:14.052Z"}
innogy-smarthome.0 | 2021-05-11 10:33:42.787 | warn | (1232) Unknown state (please report to dev):chargingCycles {"name":"chargingCycles","value":1730,"lastchanged":"2021-05-10T18:00:14.052Z"}
innogy-smarthome.0 | 2021-05-11 10:33:42.787 | warn | (1232) Unknown state (please report to dev):batteryLevel {"name":"batteryLevel","value":100,"lastchanged":"2021-05-10T18:00:14.052Z"}
innogy-smarthome.0 | 2021-05-11 10:33:42.787 | warn | (1232) Unknown state (please report to dev):situationFlags {"name":"situationFlags","value":"{\"OperationPermited\":true,\"BatteryWeak\":false,\"BatteryFailure\":false,\"BatteryFailureSticky\":false,\
innogy-smarthome.0 | 2021-05-11 10:33:42.786 | warn | (1232) Unknown state (please report to dev):operationTimeBlade {"name":"operationTimeBlade","value":100321,"lastchanged":"2021-05-10T18:00:14.061Z"}
innogy-smarthome.0 | 2021-05-11 10:33:42.786 | warn | (1232) Unknown state (please report to dev):operationTimeWR {"name":"operationTimeWR","value":110690,"lastchanged":"2021-05-10T18:00:14.061Z"}
innogy-smarthome.0 | 2021-05-11 10:33:42.786 | warn | (1232) Unknown state (please report to dev):operationTimeWL {"name":"operationTimeWL","value":110695,"lastchanged":"2021-05-10T18:00:14.061Z"}
innogy-smarthome.0 | 2021-05-11 10:33:42.786 | warn | (1232) Unknown state (please report to dev):bladeServiceTime {"name":"bladeServiceTime","value":76,"lastchanged":"2021-05-10T18:00:14.061Z"}
innogy-smarthome.0 | 2021-05-11 10:33:42.785 | warn | (1232) Unknown state (please report to dev):totalMowingTime {"name":"totalMowingTime","value":105611,"lastchanged":"2021-05-10T18:00:14.061Z"}
innogy-smarthome.0 | 2021-05-11 10:33:42.785 | warn | (1232) Unknown state (please report to dev):mowingCycles {"name":"mowingCycles","value":2308,"lastchanged":"2021-05-10T18:00:14.061Z"}
innogy-smarthome.0 | 2021-05-11 10:33:42.785 | warn | (1232) Unknown state (please report to dev):operatingTime {"name":"operatingTime","value":1470111,"lastchanged":"2021-05-10T18:00:14.061Z"}
innogy-smarthome.0 | 2021-05-11 10:33:42.785 | warn | (1232) Unknown state (please report to dev):subStatus {"name":"subStatus","value":"READY","lastchanged":"2021-05-10T18:00:14.060Z"}
innogy-smarthome.0 | 2021-05-11 10:33:42.784 | warn | (1232) Unknown state (please report to dev):mowerStatus {"name":"mowerStatus","value":"IDLE_BASE_STATION","lastchanged":"2021-05-10T18:00:14.060Z"}
innogy-smarthome.0 | 2021-05-11 10:33:42.784 | warn | (1232) Unknown state (please report to dev):action {"name":"action","value":"STOP_MOWING","lastchanged":"2021-05-10T18:00:14.058Z"}
innogy-smarthome.0 | 2021-05-11 10:33:42.784 | warn | (1232) Unknown state (please report to dev):tiltSlope {"name":"tiltSlope","value":22,"lastchanged":"2021-05-10T18:00:14.058Z"}
innogy-smarthome.0 | 2021-05-11 10:33:42.784 | warn | (1232) Unknown state (please report to dev):remainingOperationTime {"name":"remainingOperationTime","value":0,"lastchanged":"2021-05-10T18:00:14.058Z"}
innogy-smarthome.0 | 2021-05-11 10:33:42.783 | warn | (1232) Unknown state (please report to dev):nextOperationStartTime {"name":"nextOperationStartTime","value":900,"lastchanged":"2021-05-10T18:00:14.058Z"}
innogy-smarthome.0 | 2021-05-11 10:33:42.783 | warn | (1232) Unknown state (please report to dev):rainDelay {"name":"rainDelay","value":90,"lastchanged":"2021-05-10T18:00:14.058Z"}
innogy-smarthome.0 | 2021-05-11 10:33:42.783 | warn | (1232) Unknown state (please report to dev):rainSensor {"name":"rainSensor","value":true,"lastchanged":"2021-05-10T18:00:14.058Z"}
innogy-smarthome.0 | 2021-05-11 10:33:42.782 | warn | (1232) Unknown state (please report to dev):isSmokeAlarm {"name":"isSmokeAlarm","value":false,"lastchanged":"2021-05-08T12:23:46.672Z"}
innogy-smarthome.0 | 2021-05-11 10:33:42.782 | warn | (1232) Unknown state (please report to dev):isSmokeAlarm {"name":"isSmokeAlarm","value":false,"lastchanged":"2021-04-08T14:53:54.839Z"}
innogy-smarthome.0 | 2021-05-11 10:33:42.781 | warn | (1232) Unknown state (please report to dev):isSmokeAlarm {"name":"isSmokeAlarm","value":false,"lastchanged":"2021-05-10T09:36:37.149Z"}
innogy-smarthome.0 | 2021-05-11 10:33:42.781 | warn | (1232) Unknown state (please report to dev):isSmokeAlarm {"name":"isSmokeAlarm","value":false,"lastchanged":"2021-05-09T09:03:52.782Z"}
innogy-smarthome.0 | 2021-05-11 10:33:42.780 | warn | (1232) Unknown state (please report to dev):isSmokeAlarm {"name":"isSmokeAlarm","value":false,"lastchanged":"2021-04-29T08:53:21.529Z"}
innogy-smarthome.0 | 2021-05-11 10:33:42.780 | warn | (1232) Unknown state (please report to dev):HTTPResponseStatus {"name":"HTTPResponseStatus","value":"Success","lastchanged":"2021-04-08T15:09:33.915Z"}
innogy-smarthome.0 | 2021-05-11 10:33:42.779 | warn | (1232) Unknown state (please report to dev):isSending {"name":"isSending","value":false,"lastchanged":"2021-04-08T15:09:33.915Z"}
innogy-smarthome.0 | 2021-05-11 10:33:42.778 | warn | (1232) Unknown state (please report to dev):isOn {"name":"isOn","value":false,"lastchanged":"2021-04-06T18:57:11.703Z"}
innogy-smarthome.0 | 2021-05-11 10:33:42.778 | warn | (1232) Unknown state (please report to dev):activeChannel {"name":"activeChannel","value":"None","lastchanged":"2021-04-06T18:57:19.075Z"}
innogy-smarthome.0 | 2021-05-11 10:33:42.764 | info | (1232) Initialization sequence completed: found 58 devices
innogy-smarthome.0 | 2021-05-11 10:33:35.360 | info | (1232) starting. Version 0.3.6 in C:/iobroker/GLT/node_modules/iobroker.innogy-smarthome, node: v14.16.0, js-controller: 3.3.8
host.GLT(GLT) | 2021-05-11 10:33:32.660 | info | instance system.adapter.innogy-smarthome.0 started with pid 1232
host.GLT(GLT) | 2021-05-11 10:33:02.635 | info | Restart adapter system.adapter.innogy-smarthome.0 because enabled

</body>
</html>`

**Comment by Apollon77** [comment]
Please try GitHub version, manually restart adapter afterwards delete affected objects before manually! fixed?

**Comment by Apollon77** [comment]
@JBSullivan ??

**Comment by JBSullivan** [comment]
Hab ich was falsch gemacht oder wartest du auf Rückmeldung?

Sauger läuft gerade und gibt diese Fehlermeldung aus. Um jeden DP zu triggern muss ich erst einmal alle Betriebszustände anfahren oder simulieren. Kann also sein, das Kleckerweise immer nochmal das eine oder andere hinterher kommt.

Aktuell ist es nur noch dieser hier.

`
<html>
<body>


roomba.0 | 2021-07-20 11:35:22.064 | info | (9004) State value to set for "roomba.0.missions.current.runtime" has to be type "string" but received type "number"
-- | -- | -- | --
roomba.0 | 2021-07-20 11:35:21.281 | info | (9004) State value to set for "roomba.0.missions.current.runtime" has to be type "string" but received type "number"
roomba.0 | 2021-07-20 11:35:20.434 | info | (9004) State value to set for "roomba.0.missions.current.runtime" has to be type "string" but received type "number"
roomba.0 | 2021-07-20 11:35:19.635 | info | (9004) State value to set for "roomba.0.missions.current.runtime" has to be type "string" but received type "number"
roomba.0 | 2021-07-20 11:35:18.079 | info | (9004) State value to set for "roomba.0.missions.current.runtime" has to be type "string" but received type "number"
roomba.0 | 2021-07-20 11:35:17.308 | info | (9004) State value to set for "roomba.0.missions.current.runtime" has to be type "string" but received type "number"
roomba.0 | 2021-07-20 11:35:16.457 | info | (9004) State value to set for "roomba.0.missions.current.runtime" has to be type "string" but received type "number"


</body>
</html>`

**Comment by Apollon77** [comment]
Cool, runtime was fixed in latest Github verison alreayd... maybe you need to delete the object once :-(

Then I cloose here. simply open new issues for new cases

**Comment by Apollon77** [comment]
Ijust can't release it :-(

@PArns Can you please give me NPM rights?!

**Comment by JBSullivan** [comment]
Sorry, ich habe gerade gesehen, das dass hier der Innogy Adapter ist. Die Meldungen vom Beitrag #1 sind gefixt. Da kommt nichts mehr. Was ich vor 10 Minuten gepostet habe betrifft den roomba Adapter - ich bin ein wenig verwirrt heute :(

**Comment by PArns** [comment]
@Apollon77 done ...

**Comment by Apollon77** [comment]
@PArns hm ... npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/iobroker.innogy-smarthome - You do not have permission to publish "iobroker.innogy-smarthome". Are you logged in as the correct user?

**Comment by PArns** [comment]
![image](https://user-images.githubusercontent.com/16665112/126305990-51f01886-18ba-40f1-863e-f36e3043458d.png)
 @Apollon77  Was soll ich dir noch mehr an Rechten geben? ;)

**Comment by Apollon77** [comment]
Hm ... komisch ...  Ich versuchs nochmal. siehst DU mich auch auf https://www.npmjs.com/package/iobroker.innogy-smarthome ... ich nicht ... vllt caching
