### ISSUE TITLE
Port 3000 für Authentifizierung wird auch von Grafana belegt

### ISSUE THREAD

**Issue by JBSullivan** [PArns/ioBroker.innogy-smarthome#56]
Ich musste mich heute in ioBroker am Innogy Adapter neu authentifizieren, weil ich eine neue Zentrale bekommen habe. Offensichtlich läuft der Authentifizierungsprozess über den Port 3000, welcher auch von Grafana Standardmäßig benutzt wird.

Nach dem anklicken des Login Fenster, landete man im Anschluss in einem Grafana Fenster. Wenn man Grafana gestoppt hatte, konnte man die Authentifizierung problemlos bis zum Ende abschließen.

Der Knackpunkt ist also scheinbar der Port 3000. Ein ähnliches Problem gab es auch mal mit einem anderen ioB Adapter.

**Comment by Apollon77** [comment]
Ok, so I can add to readme that port 3000 is needed.
