### ISSUE TITLE
Crash when a devices has "." at the end of it's name

### ISSUE THREAD

**Issue by AlJoh55** [PArns/ioBroker.innogy-smarthome#59]
Sorry I'm not a expert, I’m only a user.

Innogy adapter is green for approximately 5 sec. and then it is stopped with: 

-	error: host.ubuntserver instance system.adapter.innogy-smarthome.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
-	info: host.ubuntserver Restart adapter system.adapter.innogy-smarthome.0 because enabled
-	warn: host.ubuntserver Do not restart adapter system.adapter.innogy-smarthome.0 because restart loop detected

Attached please find the protocol file.
[Innogy adapter restart loop.txt](https://github.com/PArns/ioBroker.innogy-smarthome/files/6970159/Innogy.adapter.restart.loop.txt)

**Comment by Apollon77** [comment]
Could it be that you have named a device with a "." at the end (Zzz-Reserve-Zuh.) Change that please

**Comment by AlJoh55** [comment]
o.k. done.thank's
-------- Ursprüngliche Nachricht --------Von: Ingo Fischer ***@***.***> Datum: 18.11.21  22:57  (GMT+01:00) An: "PArns/ioBroker.innogy-smarthome" ***@***.***> Cc: AlJoh55 ***@***.***>, Author ***@***.***> Betreff: Re: [PArns/ioBroker.innogy-smarthome] Restart loop based on
  controller v3.3 / admin5.x (#59) 
Could it be that you have named a device with a "." at the end (Zzz-Reserve-Zuh.) Change that please

**Comment by Apollon77** [comment]
I would still leave the issue open till we find time to prevent such crashes in such a case
