### ISSUE TITLE
Seit heute die folgenden Warmeldungen

### ISSUE THREAD

**Issue by JBSullivan** [PArns/ioBroker.innogy-smarthome#63]
Haben die Warnmeldungen ggf. etwas hiermit zu tun?  Adapter Version ist 0.3.7

Re: [PArns/ioBroker.innogy-smarthome] Bump mocha from 9.0.2 to 9.1.2(#61)

`<html>
<body>

innogy-smarthome.0 | 2021-11-01 10:10:05.188 | warn | setObject Garten.Wall-E.NextOperationStartTime (type=state) property common.role missing!
-- | -- | -- | --
innogy-smarthome.0 | 2021-11-01 10:10:05.187 | warn | Unknown state (please report to dev):nextOperationStartTime {"name":"nextOperationStartTime","value":0,"lastchanged":"1970-01-01T00:00:00.000Z"}
innogy-smarthome.0 | 2021-11-01 10:10:05.187 | warn | setObject Garten.Wall-E.EcoMode (type=state) property common.role missing!
innogy-smarthome.0 | 2021-11-01 10:10:05.187 | warn | Unknown state (please report to dev):ecoMode {"name":"ecoMode","value":0,"lastchanged":"1970-01-01T00:00:00.000Z"}
innogy-smarthome.0 | 2021-11-01 10:10:05.186 | warn | setObject Garten.Wall-E.CuttingHeight (type=state) property common.role missing!
innogy-smarthome.0 | 2021-11-01 10:10:05.186 | warn | Unknown state (please report to dev):cuttingHeight {"name":"cuttingHeight","value":30,"lastchanged":"1970-01-01T00:00:00.000Z"}
innogy-smarthome.0 | 2021-11-01 10:10:05.185 | warn | setObject Garten.Wall-E.Action (type=state) property common.role missing!
innogy-smarthome.0 | 2021-11-01 10:10:05.185 | warn | Unknown state (please report to dev):action {"name":"action","value":"START_HOMING_FROM_IDLE","lastchanged":"2021-10-31T16:08:44.600Z"}
innogy-smarthome.0 | 2021-11-01 10:10:05.184 | warn | setObject Garten.Wall-E.ErrorDescription (type=state) property common.role missing!
innogy-smarthome.0 | 2021-11-01 10:10:05.184 | warn | Unknown state (please report to dev):errorDescription {"name":"errorDescription","value":"CN999;ISSUE;UNKNOWN","lastchanged":"2021-10-06T12:39:55.318Z"}
innogy-smarthome.0 | 2021-11-01 10:10:05.183 | warn | setObject Garten.Wall-E.ChargingCycles (type=state) property common.role missing!
innogy-smarthome.0 | 2021-11-01 10:10:05.183 | warn | Unknown state (please report to dev):chargingCycles {"name":"chargingCycles","value":1885,"lastchanged":"2021-10-31T12:04:09.420Z"}
innogy-smarthome.0 | 2021-11-01 10:10:05.182 | warn | setObject Garten.Wall-E.ChargingCurrent (type=state) property common.role missing!
innogy-smarthome.0 | 2021-11-01 10:10:05.182 | warn | Unknown state (please report to dev):chargingCurrent {"name":"chargingCurrent","value":2500,"lastchanged":"2021-10-04T10:51:22.497Z"}
innogy-smarthome.0 | 2021-11-01 10:10:05.182 | warn | setObject Garten.Wall-E.BatteryLevel (type=state) property common.role missing!
innogy-smarthome.0 | 2021-11-01 10:10:05.181 | warn | Unknown state (please report to dev):batteryLevel {"name":"batteryLevel","value":100,"lastchanged":"2021-10-31T13:19:14.399Z"}
innogy-smarthome.0 | 2021-11-01 10:10:05.180 | warn | setObject Büro.Rauchmelder-Büro.IsSmokeAlarm (type=state) property common.role missing!
innogy-smarthome.0 | 2021-11-01 10:10:05.180 | warn | Unknown state (please report to dev):isSmokeAlarm {"name":"isSmokeAlarm","value":false,"lastchanged":"1970-01-01T00:00:00.000Z"}
innogy-smarthome.0 | 2021-11-01 10:10:05.179 | warn | setObject Garten.Rauchmelder-E-Bike-Ladestation.IsSmokeAlarm (type=state) property common.role missing!
innogy-smarthome.0 | 2021-11-01 10:10:05.178 | warn | Unknown state (please report to dev):isSmokeAlarm {"name":"isSmokeAlarm","value":false,"lastchanged":"1970-01-01T00:00:00.000Z"}
innogy-smarthome.0 | 2021-11-01 10:10:05.177 | warn | setObject Flur.Rauchmelder-Flur-OG.IsSmokeAlarm (type=state) property common.role missing!
innogy-smarthome.0 | 2021-11-01 10:10:05.176 | warn | Unknown state (please report to dev):isSmokeAlarm {"name":"isSmokeAlarm","value":false,"lastchanged":"1970-01-01T00:00:00.000Z"}
innogy-smarthome.0 | 2021-11-01 10:10:05.174 | warn | setObject Kinderzimmer-OG.Rauchmelder.IsSmokeAlarm (type=state) property common.role missing!
innogy-smarthome.0 | 2021-11-01 10:10:05.173 | warn | Unknown state (please report to dev):isSmokeAlarm {"name":"isSmokeAlarm","value":false,"lastchanged":"1970-01-01T00:00:00.000Z"}
innogy-smarthome.0 | 2021-11-01 10:10:05.172 | warn | setObject Keller.Rauchmelder-Speicher.IsSmokeAlarm (type=state) property common.role missing!
innogy-smarthome.0 | 2021-11-01 10:10:05.171 | warn | Unknown state (please report to dev):isSmokeAlarm {"name":"isSmokeAlarm","value":false,"lastchanged":"1970-01-01T00:00:00.000Z"}
innogy-smarthome.0 | 2021-11-01 10:10:05.170 | warn | setObject Ankleidezimmer.Rauchmelder.IsSmokeAlarm (type=state) property common.role missing!
innogy-smarthome.0 | 2021-11-01 10:10:05.169 | warn | Unknown state (please report to dev):isSmokeAlarm {"name":"isSmokeAlarm","value":false,"lastchanged":"1970-01-01T00:00:00.000Z"}
innogy-smarthome.0 | 2021-11-01 10:10:05.168 | warn | setObject Flur.Rauchmelder-Flur.IsSmokeAlarm (type=state) property common.role missing!
innogy-smarthome.0 | 2021-11-01 10:10:05.167 | warn | Unknown state (please report to dev):isSmokeAlarm {"name":"isSmokeAlarm","value":false,"lastchanged":"1970-01-01T00:00:00.000Z"}
innogy-smarthome.0 | 2021-11-01 10:10:05.165 | warn | setObject Variable.HTTP-Anfrage.IsSending (type=state) property common.role missing!
innogy-smarthome.0 | 2021-11-01 10:10:05.164 | warn | Unknown state (please report to dev):isSending {"name":"isSending","value":false,"lastchanged":"2021-11-01T05:44:40.687Z"}
innogy-smarthome.0 | 2021-11-01 10:10:05.163 | warn | setObject Variable.HTTP-Anfrage.HTTPResponseStatus (type=state) property common.role missing!
innogy-smarthome.0 | 2021-11-01 10:10:05.158 | warn | Unknown state (please report to dev):HTTPResponseStatus {"name":"HTTPResponseStatus","value":"Success","lastchanged":"2021-11-01T05:44:40.686Z"}
innogy-smarthome.0 | 2021-11-01 10:10:05.157 | warn | setObject Garten.Alarmsirene.ActiveChannel (type=state) property common.role missing!
innogy-smarthome.0 | 2021-11-01 10:10:05.156 | warn | Unknown state (please report to dev):activeChannel {"name":"activeChannel","value":"None","lastchanged":"1970-01-01T00:00:00.000Z"}
innogy-smarthome.0 | 2021-11-01 10:10:05.156 | warn | setObject Garten.Alarmsirene.IsOn (type=state) property common.role missing!
innogy-smarthome.0 | 2021-11-01 10:10:05.155 | warn | Unknown state (please report to dev):isOn {"name":"isOn","value":false,"lastchanged":"1970-01-01T00:00:00.000Z"}

</body>
</html>`

**Comment by Benno-O** [comment]
Habe die gleiche Warnmeldung. Außerdem startet der Adapter jede Minute neu. Irgendeine Idee woher der Neustart exakt jede Minute kommt?

**Comment by Apollon77** [comment]
Restart jede Minjute: Versehentlich einen restar schedule konfiguriert?
