### ISSUE TITLE
Datenpunkt Nachrichten

### ISSUE THREAD

**Issue by Castlehub** [PArns/ioBroker.innogy-smarthome#67]
Ist es möglich über den Adapter auch die Nachrichten der Zentrale abzurufen?

MfG

**Comment by Apollon77** [comment]
Die nächste version wird das tun, aber nur ausgewählte verarbeite (lowBattery, isReachable) ... Was wird mehr benötigt?

**Comment by Apollon77** [comment]
1.00 will process messages for lowBattery and isUnreachable ... I close here. Please open new issues for relevant messages, see also https://forum.iobroker.net/topic/61351/livisi-innogy-smarthome-adapter-1-0-0-breaking
