### ISSUE TITLE
[0.4.0] iobroker / keine Authorisation möglich (authoriation - blank page)

### ISSUE THREAD

**Issue by vsa-d** [PArns/ioBroker.innogy-smarthome#72]
Hallo,
seit dem Update auf 0.4.0. kan ich mich nciht mehr authorisieren (iobroker, aktuellste Version). Es erscheint eine leere Seite. 
(ausprobiert mit firefox, chrome, edge-Win11)
Bitte um Hilfe.

**Comment by JBSullivan** [comment]
Bist du Beta Tester und dir wurde von Livisi die Zentrale für das Update auf locale Smarthome freigeschaltet?  

Geh mal in die Adapter Instanz und schau dir die neue Konfig Seite des Adapters an. Da gibt es jetzt 2 Login Möglichkeiten. Kann sein, das du dich ggf. nochmal neu an der alten Cloud Autorisieren musst. 
Das Locale SmartHome ist nur für einen kleinen Personenkreis von 21 Leuten frei geschaltet - die Beta Tester. Nur die werden mit dem unteren Teil des Adapter Logins eine Verbindung zur Zentrale bekommen.

**Comment by PArns** [comment]
Nein dies ist in der Tat gerade ein Bug. Sobald die lokale Verbindung aktiv ist, erscheint eine leere Seite. Das Problem sollte in ein paar Minuten bzw. mit dem nächsten Update behoben sein

**Comment by PArns** [comment]
Fixed in 0.4.1
