### ISSUE TITLE
0.4.0 - Betatest Livisi Zentrale 

### ISSUE THREAD

**Issue by JBSullivan** [PArns/ioBroker.innogy-smarthome#73]
Seit dem Update der Zentrale (2.0) und des Adapters spamt mir dieser das LOG mit den folgenden Meldungen im Sekundentakt zu.

Ich glaube die gleichen Meldungen gab es auch schon zu Zeiten der 0.3.x - da jedoch nicht in der Häufigkeit

`<html>
<body>

innogy-smarthome.0 | 17480 | 2022-03-02 16:36:56.119 | warn | setObject Büro.Rauchmelder-Büro.IsSmokeAlarm (type=state) property common.role missing!
-- | -- | -- | -- | --
innogy-smarthome.0 | 17480 | 2022-03-02 16:36:56.119 | warn | Unknown state (please report to dev):isSmokeAlarm {"name":"isSmokeAlarm","value":false,"lastchanged":"1970-01-01T00:00:00.000Z"}
innogy-smarthome.0 | 17480 | 2022-03-02 16:36:56.119 | warn | setObject Garten.Rauchmelder-E-Bike-Ladestation.IsSmokeAlarm (type=state) property common.role missing!
innogy-smarthome.0 | 17480 | 2022-03-02 16:36:56.119 | warn | Unknown state (please report to dev):isSmokeAlarm {"name":"isSmokeAlarm","value":false,"lastchanged":"1970-01-01T00:00:00.000Z"}
innogy-smarthome.0 | 17480 | 2022-03-02 16:36:56.119 | warn | setObject Flur.Rauchmelder-Flur-OG.IsSmokeAlarm (type=state) property common.role missing!
innogy-smarthome.0 | 17480 | 2022-03-02 16:36:56.119 | warn | Unknown state (please report to dev):isSmokeAlarm {"name":"isSmokeAlarm","value":false,"lastchanged":"1970-01-01T00:00:00.000Z"}
innogy-smarthome.0 | 17480 | 2022-03-02 16:36:56.119 | warn | setObject Kinderzimmer-OG.Rauchmelder.IsSmokeAlarm (type=state) property common.role missing!
innogy-smarthome.0 | 17480 | 2022-03-02 16:36:56.118 | warn | Unknown state (please report to dev):isSmokeAlarm {"name":"isSmokeAlarm","value":false,"lastchanged":"1970-01-01T00:00:00.000Z"}
innogy-smarthome.0 | 17480 | 2022-03-02 16:36:56.118 | warn | setObject Keller.Rauchmelder-Speicher.IsSmokeAlarm (type=state) property common.role missing!
innogy-smarthome.0 | 17480 | 2022-03-02 16:36:56.118 | warn | Unknown state (please report to dev):isSmokeAlarm {"name":"isSmokeAlarm","value":false,"lastchanged":"1970-01-01T00:00:00.000Z"}
innogy-smarthome.0 | 17480 | 2022-03-02 16:36:56.118 | warn | setObject Ankleidezimmer.Rauchmelder.IsSmokeAlarm (type=state) property common.role missing!
innogy-smarthome.0 | 17480 | 2022-03-02 16:36:56.118 | warn | Unknown state (please report to dev):isSmokeAlarm {"name":"isSmokeAlarm","value":false,"lastchanged":"1970-01-01T00:00:00.000Z"}
innogy-smarthome.0 | 17480 | 2022-03-02 16:36:56.115 | warn | setObject Flur.Rauchmelder-Flur.IsSmokeAlarm (type=state) property common.role missing!
innogy-smarthome.0 | 17480 | 2022-03-02 16:36:56.115 | warn | Unknown state (please report to dev):isSmokeAlarm {"name":"isSmokeAlarm","value":false,"lastchanged":"1970-01-01T00:00:00.000Z"}
innogy-smarthome.0 | 17480 | 2022-03-02 16:36:56.115 | warn | setObject Variable.HTTP-Anfrage.IsSending (type=state) property common.role missing!
innogy-smarthome.0 | 17480 | 2022-03-02 16:36:56.115 | warn | Unknown state (please report to dev):isSending {"name":"isSending","value":false,"lastchanged":"2022-03-01T17:13:16.026Z"}
innogy-smarthome.0 | 17480 | 2022-03-02 16:36:56.115 | warn | setObject Variable.HTTP-Anfrage.HTTPResponseStatus (type=state) property common.role missing!
innogy-smarthome.0 | 17480 | 2022-03-02 16:36:56.115 | warn | Unknown state (please report to dev):HTTPResponseStatus {"name":"HTTPResponseStatus","value":"Success","lastchanged":"2022-03-01T17:13:16.025Z"}
innogy-smarthome.0 | 17480 | 2022-03-02 16:36:56.114 | warn | setObject Garten.Alarmsirene.ActiveChannel (type=state) property common.role missing!
innogy-smarthome.0 | 17480 | 2022-03-02 16:36:56.114 | warn | Unknown state (please report to dev):activeChannel {"name":"activeChannel","value":"None","lastchanged":"1970-01-01T00:00:00.000Z"}
innogy-smarthome.0 | 17480 | 2022-03-02 16:36:56.114 | warn | setObject Garten.Alarmsirene.IsOn (type=state) property common.role missing!
innogy-smarthome.0 | 17480 | 2022-03-02 16:36:56.114 | warn | Unknown state (please report to dev):isOn {"name":"isOn","value":false,"lastchanged":"1970-01-01T00:00:00.000Z"}
innogy-smarthome.0 | 17480 | 2022-03-02 16:36:56.109 | info | Initialization sequence completed: found 63 devices
innogy-smarthome.0 | 17480 | 2022-03-02 16:36:55.202 | error | STACK:RangeError: Invalid WebSocket frame: invalid status code 0 at Receiver.controlMessage (C:\iobroker\GLT\node_modules\innogy-smarthome-lib\node_modules\ws\lib\receiver.js:449:18) at Receiver.getData (C:\iobroker\GLT\node_modules\innogy-smarthome-lib\node_modules\ws\lib\receiver.js:335:42) at Receiver.startLoop (C:\iobroker\GLT\node_modules\innogy-smarthome-lib\node_modules\ws\lib\receiver.js:138:22) at Receiver._write (C:\iobroker\GLT\node_modules\innogy-smarthome-lib\node_modules\ws\lib\receiver.js:74:10) at writeOrBuffer (internal/streams/writable.js:358:12) at Receiver.Writable.write (internal/streams/writable.js:303:10) at Socket.socketOnData (C:\iobroker\GLT\node_modules\innogy-smarthome-lib\node_modules\ws\lib\websocket.js:864:35) at Socket.emit (events.js:315:20) at addChunk (internal/streams/readable.js:309:12) at readableAddChunk (internal/streams/readable.js:284:9) at Socket.Readable.push (internal/streams/readable.js:223:10) at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
innogy-smarthome.0 | 17480 | 2022-03-02 16:36:55.201 | error | GOT AN ERROR:{}

</body>
</html>`

**Comment by PArns** [comment]
Hi, schau mal bitte, ob das Problem mit 0.4.1 behoben ist ... Ich habe gerade einige States noch geadded

**Comment by JBSullivan** [comment]
Wie schon im Livisi Forum geschrieben, sieht es bis jetzt immer noch sehr sehr gut aus 👍👍👍 Absolut keine Meldungen mehr. Mähroboter konnte ich aber noch nicht testen, was dann ggf. für Meldungen kommen (oder auch nicht), wenn dieser wieder in Betrieb ist

**Comment by JBSullivan** [comment]
Ich habe heute morgen im LOG festgestellt, das alle paar Minuten (nicht reproduzierbar) die Eintragungen kommen. Ich schalte gleich mal auf DEBUG und gucke was noch mit übertragen wird.

`<html>
<body>


innogy-smarthome.0 | 2022-03-03 09:11:20.402 | info | Initialization sequence completed: found 63 devices
-- | -- | -- | --
innogy-smarthome.0 | 2022-03-03 09:11:20.211 | info | Initialization sequence completed: found 63 devices
innogy-smarthome.0 | 2022-03-03 09:10:18.926 | info | Initialization sequence completed: found 63 devices
innogy-smarthome.0 | 2022-03-03 09:10:18.584 | info | Initialization sequence completed: found 63 devices
innogy-smarthome.0 | 2022-03-03 09:09:17.418 | info | Initialization sequence completed: found 63 devices
innogy-smarthome.0 | 2022-03-03 09:09:17.237 | info | Initialization sequence completed: found 63 devices


</body>
</html>`


`<html>
<body>


innogy-smarthome.0 | 2022-03-03 09:16:25.223 | error | STACK:RangeError: Invalid WebSocket frame: invalid status code 0 at Receiver.controlMessage (C:\iobroker\GLT\node_modules\innogy-smarthome-lib\node_modules\ws\lib\receiver.js:449:18) at Receiver.getData (C:\iobroker\GLT\node_modules\innogy-smarthome-lib\node_modules\ws\lib\receiver.js:335:42) at Receiver.startLoop (C:\iobroker\GLT\node_modules\innogy-smarthome-lib\node_modules\ws\lib\receiver.js:138:22) at Receiver._write (C:\iobroker\GLT\node_modules\innogy-smarthome-lib\node_modules\ws\lib\receiver.js:74:10) at writeOrBuffer (internal/streams/writable.js:358:12) at Receiver.Writable.write (internal/streams/writable.js:303:10) at Socket.socketOnData (C:\iobroker\GLT\node_modules\innogy-smarthome-lib\node_modules\ws\lib\websocket.js:864:35) at Socket.emit (events.js:315:20) at addChunk (internal/streams/readable.js:309:12) at readableAddChunk (internal/streams/readable.js:284:9) at Socket.Readable.push (internal/streams/readable.js:223:10) at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
-- | -- | -- | --
innogy-smarthome.0 | 2022-03-03 09:16:25.222 | error | GOT AN ERROR:{}


</body>
</html>`

**Comment by JBSullivan** [comment]
So, Mähroboter (Robolinho3000) wieder in Betrieb genommen, aber trotz neuem Treiber beim Frmware Update der Zentrale, wirft dieser (immer noch) die folgenden Meldungen, mit dem Hinweis "Report an DEV"

`<html>
<body>


innogy-smarthome.0 | 18380 | 2022-03-03 16:54:52.487 | debug | OPEN
-- | -- | -- | -- | --
innogy-smarthome.0 | 18380 | 2022-03-03 16:54:51.923 | debug | SOCKET CONNECTION TO THE INNOGY API WAS CLOSED
innogy-smarthome.0 | 18380 | 2022-03-03 16:54:51.922 | error | STACK:RangeError: Invalid WebSocket frame: invalid status code 0 at Receiver.controlMessage (C:\iobroker\GLT\node_modules\innogy-smarthome-lib\node_modules\ws\lib\receiver.js:449:18) at Receiver.getData (C:\iobroker\GLT\node_modules\innogy-smarthome-lib\node_modules\ws\lib\receiver.js:335:42) at Receiver.startLoop (C:\iobroker\GLT\node_modules\innogy-smarthome-lib\node_modules\ws\lib\receiver.js:138:22) at Receiver._write (C:\iobroker\GLT\node_modules\innogy-smarthome-lib\node_modules\ws\lib\receiver.js:74:10) at writeOrBuffer (internal/streams/writable.js:358:12) at Receiver.Writable.write (internal/streams/writable.js:303:10) at Socket.socketOnData (C:\iobroker\GLT\node_modules\innogy-smarthome-lib\node_modules\ws\lib\websocket.js:864:35) at Socket.emit (events.js:315:20) at addChunk (internal/streams/readable.js:309:12) at readableAddChunk (internal/streams/readable.js:284:9) at Socket.Readable.push (internal/streams/readable.js:223:10) at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
innogy-smarthome.0 | 18380 | 2022-03-03 16:54:51.922 | error | GOT AN ERROR:{}
innogy-smarthome.0 | 18380 | 2022-03-03 16:54:51.918 | debug | SOCKET CONNECTION TO THE INNOGY API WAS CLOSED
innogy-smarthome.0 | 18380 | 2022-03-03 16:54:51.917 | debug | DEBUG EVENT {"type":"error_handler","data":{"name":"StatusCodeError","statusCode":400,"message":"400 - {\"errorcode\":1005,\"description\":\"Missing argument or wrong value\",\"messages\":[\"Parameter [ pointTemperature ] has invalid value: Value too small: [ 0 ]. The value is expected to fall in the following interval: {\\\"bounds\\\":\\\"6 <= x <= 30\\\"}\"]}","error":{"errorcode":1005,"description":"Missing argument or wrong value","messages":["Parameter [ pointTemperature ] has invalid value: Value too small: [ 0 ]. The value is expected to fall in the following interval: {\"bounds\":\"6 <= x <= 30\"}"]},"options":{"method":"POST","uri":"http://10.122.60.111:8080/action","body":{"type":"SetState","namespace":"core.RWE","target":"/capability/85c12f3795394f3ab5a6dcde50de1894","params":{"pointTemperature":{"type":"Constant","value":0}}},"json":true,"headers":{"Authorization":"Hier steht sonst Code"},"simple":true,"resolveWithFullResponse":false,"transform2xxOnly":false},"response":{"statusCode":400,"body":{"errorcode":1005,"description":"Missing argument or wrong value","messages":["Parameter [ pointTemperature ] has invalid value: Value too small: [ 0 ]. The value is expected to fall in the following interval: {\"bounds\":\"6 <= x <= 30\"}"]},"headers":{"access-control-allow-origin":"*","content-type":"application/json","content-length":"245"},"request":{"uri":{"protocol":"http:","slashes":true,"auth":null,"host":"10.122.60.111:8080","port":"8080","hostname":"10.122.60.111","hash":null,"search":null,"query":null,"pathname":"/action","path":"/action","href":"http://10.122.60.111:8080/action"},"method":"POST","headers":{"Authorization":"Hier steht sonst Code","accept":"application/json","content-type":"application/json","content-length":158}}}}}
innogy-smarthome.0 | 18380 | 2022-03-03 16:54:51.887 | debug | OPEN
innogy-smarthome.0 | 18380 | 2022-03-03 16:54:51.482 | warn | Unknown state (please report to dev):totalMowingTime {"name":"totalMowingTime","value":113987,"lastchanged":"2022-03-03T15:54:50.631Z"}
innogy-smarthome.0 | 18380 | 2022-03-03 16:54:51.481 | warn | Unknown state (please report to dev):subStatus {"name":"subStatus","value":"READY","lastchanged":"2022-03-03T15:38:50.361Z"}
innogy-smarthome.0 | 18380 | 2022-03-03 16:54:51.481 | warn | Unknown state (please report to dev):situationFlags {"name":"situationFlags","value":"{\"OperationPermitted\": true,\"BatteryWeak\": false,\"BatteryFailure\": false,\"BatteryFailureSticky\": false,\"MowingWindow\": false,\"MargingMowingCompleted\": false,\"UserInteraction\": true,\"LoopSignalValid\": true,\"ChargerContact\": false,\"ChargerActive\": false,\"ChargerAllowsRestart\": false,\"ChargerFailure\": false,\"ManualOperation\": true,\"RobotIsActive\": true,\"IssueDisplay\": false,\"HommingTriggerSchedule\": false,\"HommingTriggerBatteryWeak\": false,\"HommingTriggerUserRequest\": false,\"HommingTriggerRain\": false,\"HommingTriggerTemperature\": false,\"HommingTriggerMowingUnitOverload\": false,\"HommingTriggerRestart\": false,\"DayCancelled\": false,\"RainDetected\": false,\"RainAllowsMowing\": true,\"TemperatureMonitoringActive\": true,\"TemperatureAllowsMowing\": true,\"TemperatureAllowsHoming\": true,\"TemperatureAllowsCharging\": true,\"WheelMotorTemperatureHigh\": false,\"StopAfterIssue\": false,\"BladesService\": false,\"SmarthomeActive\": false}","lastchanged":"2022-03-03T15:38:50.460Z"}
innogy-smarthome.0 | 18380 | 2022-03-03 16:54:51.481 | warn | Unknown state (please report to dev):operationTimeWR {"name":"operationTimeWR","value":122660,"lastchanged":"2022-03-03T15:54:50.744Z"}
innogy-smarthome.0 | 18380 | 2022-03-03 16:54:51.481 | warn | Unknown state (please report to dev):operationTimeWL {"name":"operationTimeWL","value":122663,"lastchanged":"2022-03-03T15:54:50.690Z"}
innogy-smarthome.0 | 18380 | 2022-03-03 16:54:51.480 | warn | Unknown state (please report to dev):operationTimeBlade {"name":"operationTimeBlade","value":111928,"lastchanged":"2022-03-03T15:54:50.796Z"}
innogy-smarthome.0 | 18380 | 2022-03-03 16:54:51.480 | warn | Unknown state (please report to dev):operatingTime {"name":"operatingTime","value":1659969,"lastchanged":"2022-03-03T15:54:50.516Z"}
innogy-smarthome.0 | 18380 | 2022-03-03 16:54:51.480 | warn | Unknown state (please report to dev):mowingCycles {"name":"mowingCycles","value":3291,"lastchanged":"2022-03-03T15:38:50.662Z"}
innogy-smarthome.0 | 18380 | 2022-03-03 16:54:51.480 | warn | Unknown state (please report to dev):mowerStatus {"name":"mowerStatus","value":"WORKING","lastchanged":"2022-03-03T15:38:50.242Z"}
innogy-smarthome.0 | 18380 | 2022-03-03 16:54:51.480 | warn | Unknown state (please report to dev):bladeServiceTime {"name":"bladeServiceTime","value":79,"lastchanged":"2022-03-03T15:37:52.494Z"}
innogy-smarthome.0 | 18380 | 2022-03-03 16:54:51.480 | warn | Unknown state (please report to dev):tiltSlope {"name":"tiltSlope","value":22,"lastchanged":"2022-03-03T15:37:51.866Z"}
innogy-smarthome.0 | 18380 | 2022-03-03 16:54:51.479 | warn | Unknown state (please report to dev):remainingOperationTime {"name":"remainingOperationTime","value":0,"lastchanged":"1970-01-01T00:00:00.000Z"}
innogy-smarthome.0 | 18380 | 2022-03-03 16:54:51.479 | warn | Unknown state (please report to dev):rainSensor {"name":"rainSensor","value":true,"lastchanged":"2022-03-03T15:37:51.919Z"}
innogy-smarthome.0 | 18380 | 2022-03-03 16:54:51.479 | warn | Unknown state (please report to dev):rainDelay {"name":"rainDelay","value":90,"lastchanged":"2022-03-03T15:37:51.976Z"}
innogy-smarthome.0 | 18380 | 2022-03-03 16:54:51.479 | warn | Unknown state (please report to dev):nextOperationStartTime {"name":"nextOperationStartTime","value":0,"lastchanged":"1970-01-01T00:00:00.000Z"}
innogy-smarthome.0 | 18380 | 2022-03-03 16:54:51.478 | warn | Unknown state (please report to dev):ecoMode {"name":"ecoMode","value":0,"lastchanged":"1970-01-01T00:00:00.000Z"}
innogy-smarthome.0 | 18380 | 2022-03-03 16:54:51.477 | warn | Unknown state (please report to dev):cuttingHeight {"name":"cuttingHeight","value":30,"lastchanged":"1970-01-01T00:00:00.000Z"}
innogy-smarthome.0 | 18380 | 2022-03-03 16:54:51.477 | warn | Unknown state (please report to dev):action {"name":"action","value":"START_MOWING_FROM_IDLE","lastchanged":"2022-03-03T15:38:51.242Z"}
innogy-smarthome.0 | 18380 | 2022-03-03 16:54:51.477 | warn | Unknown state (please report to dev):errorDescription {"name":"errorDescription","value":"CN999;ISSUE;UNKNOWN","lastchanged":"2022-03-03T15:37:51.081Z"}
innogy-smarthome.0 | 18380 | 2022-03-03 16:54:51.477 | warn | Unknown state (please report to dev):chargingCycles {"name":"chargingCycles","value":1890,"lastchanged":"2022-03-03T15:37:52.439Z"}
innogy-smarthome.0 | 18380 | 2022-03-03 16:54:51.476 | warn | Unknown state (please report to dev):chargingCurrent {"name":"chargingCurrent","value":2500,"lastchanged":"2022-03-03T15:37:51.812Z"}
innogy-smarthome.0 | 18380 | 2022-03-03 16:54:51.475 | warn | Unknown state (please report to dev):batteryLevel {"name":"batteryLevel","value":70,"lastchanged":"2022-03-03T15:55:03.398Z"}


</body>
</html>`
