### ISSUE TITLE
not possible to authorize

### ISSUE THREAD

**Issue by djmarc75** [PArns/ioBroker.innogy-smarthome#74]
since update to 0.4.1 it is not possible to authorise my account.
Device: 2nd Generation
<html><body>

host.SmartHomeZentrale | 2022-03-05 11:40:19.574 | error | instance system.adapter.innogy-smarthome.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | -- | --
innogy-smarthome.0 | 2022-03-05 11:40:18.927 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
innogy-smarthome.0 | 2022-03-05 11:40:18.926 | info | terminating
innogy-smarthome.0 | 2022-03-05 11:40:18.925 | info | cleaned everything up...
innogy-smarthome.0 | 2022-03-05 11:40:18.923 | error | Exception-Code: EADDRINUSE: listen EADDRINUSE: address already in use :::3000
innogy-smarthome.0 | 2022-03-05 11:40:18.922 | error | Error:  listen EADDRINUSE: address already in use :::3000     at Server.setupListenHandle [as _listen2] (net.js:1331:16)     at listenInCluster (net.js:1379:12)     at Server.listen (net.js:1465:7)     at Function.listen  (/opt/iobroker/node_modules/innogy-smarthome-lib/node_modules/express/lib/application.js:618:24)     at startAuthorization  (/opt/iobroker/node_modules/innogy-smarthome-lib/lib/oauth2/index.js:272:22)     at Object.startAuthorization  (/opt/iobroker/node_modules/innogy-smarthome-lib/lib/oauth2/index.js:388:20)     at  /opt/iobroker/node_modules/innogy-smarthome-lib/lib/requestor/index.js:58:41     at getAuthorizationStatus  (/opt/iobroker/node_modules/innogy-smarthome-lib/lib/oauth2/index.js:375:9)     at Object.getAuthorizationStatus  (/opt/iobroker/node_modules/innogy-smarthome-lib/lib/oauth2/index.js:385:20)     at  /opt/iobroker/node_modules/innogy-smarthome-lib/lib/requestor/index.js:56:22     at Promise.cancellationExecute [as _execute]  (/opt/iobroker/node_modules/bluebird/js/release/debuggability.js:406:9)     at Promise._resolveFromExecutor  (/opt/iobroker/node_modules/bluebird/js/release/promise.js:518:18)     at new Promise  (/opt/iobroker/node_modules/bluebird/js/release/promise.js:103:10)     at Requestor.doRequest  (/opt/iobroker/node_modules/innogy-smarthome-lib/lib/requestor/index.js:54:12)     at Requestor.call  (/opt/iobroker/node_modules/innogy-smarthome-lib/lib/requestor/index.js:48:17)     at SmartHome._location  (/opt/iobroker/node_modules/innogy-smarthome-lib/lib/smarthome/index.js:387:28)     at SmartHome.init  (/opt/iobroker/node_modules/innogy-smarthome-lib/lib/smarthome/index.js:93:17)     at initSmartHome  (/opt/iobroker/node_modules/iobroker.innogy-smarthome/main.js:221:15)     at Adapter.onMessage  (/opt/iobroker/node_modules/iobroker.innogy-smarthome/main.js:36:17)     at Adapter.emit (events.js:400:28)     at change  (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5301:34)     at Immediate.<anonymous>  (/opt/iobroker/node_modules/@iobroker/db-states-redis/lib/states/statesInRedisClient.js:322:37)
innogy-smarthome.0 | 2022-03-05 11:40:18.918 | error | uncaught exception: listen EADDRINUSE: address already in use :::3000
innogy-smarthome.0 | 2022-03-05 11:40:18.914 | warn | DEBUG:   {"server":{"_events":{},"_eventsCount":2,"_maxListeners":100,"_connections":0,"_handle":null,"_usingWorkers":false,"_workers":[],"_unref":false,"allowHalfOpen":true,"pauseOnConnect":false,"httpAllowHalfOpen":false,"timeout":0,"keepAliveTimeout":5000,"maxHeadersCount":null,"headersTimeout":60000,"requestTimeout":0},"startUri":"https://iobroker-connect.patrick-arns.de/start/?s=%7B%22authUri%22%3A%22https%3A%2F%2Fauth.services-smarthome.de%2FAUTH%2Fauthorize%3Fredirect_uri%3Dhttps%253A%252F%252Fiobroker-connect.patrick-arns.de%252F%26response_type%3Dcode%26client_id%3D61768662%22%2C%22callbackUri%22%3A%22http%3A%2F%2F192.168.178.2%3A3000%2Fauthorize%22%7D"}
innogy-smarthome.0 | 2022-03-05 11:40:18.913 | warn | Adapter is not configured or needs reauthorization! Please go to the adapter settings and start the authorization
innogy-smarthome.0 | 2022-03-05 11:40:17.945 | warn | DEBUG:   {"server":{"_events":{},"_eventsCount":2,"_maxListeners":100,"_connections":0,"_handle":{"reading":false},"_usingWorkers":false,"_workers":[],"_unref":false,"allowHalfOpen":true,"pauseOnConnect":false,"httpAllowHalfOpen":false,"timeout":0,"keepAliveTimeout":5000,"maxHeadersCount":null,"headersTimeout":60000,"requestTimeout":0,"_connectionKey":"6::::3000"},"startUri":"https://iobroker-connect.patrick-arns.de/start/?s=%7B%22authUri%22%3A%22https%3A%2F%2Fauth.services-smarthome.de%2FAUTH%2Fauthorize%3Fredirect_uri%3Dhttps%253A%252F%252Fiobroker-connect.patrick-arns.de%252F%26response_type%3Dcode%26client_id%3D61768662%22%2C%22callbackUri%22%3A%22http%3A%2F%2F192.168.178.2%3A3000%2Fauthorize%22%7D"}
innogy-smarthome.0 | 2022-03-05 11:40:17.944 | warn | Adapter is not configured or needs reauthorization! Please go to the adapter settings and start the authorization
innogy-smarthome.0 | 2022-03-05 11:40:17.893 | info | starting. Version 0.4.1 in /opt/iobroker/node_modules/iobroker.innogy-smarthome, node: v14.19.0, js-controller: 4.0.18

</body>
</html>

**Comment by JBSullivan** [comment]
Version 0.4.1 läßt auch keinen Login mehr auf die Cloud Seite zu - egal ob mit LocalHome Haken gesetzt, oder ohne. Außerdem besteht immer noch die Port Kollision ( 3000 ) mit Grafana. Um die Authorisierung durchführen zu können muss man Grafana stoppen.

![image](https://user-images.githubusercontent.com/44617472/157021620-73dbd0a0-70d5-46ae-a1c1-c5612b06deb1.png)

**Comment by djmarc75** [comment]
funtioniert jetzt bei mir mit v.0.4.5

**Comment by Matze2010** [comment]
I had the same problem. Last working version was 0.4.0. Later version didn't work due to conflicts with using port 3000. Figured it was a conflict with the socket.io adapter. Removing the socket.io adapter made it work again.
