### ISSUE TITLE
Update stable version in repo from 0.3.7 to 0.4.5

### ISSUE THREAD

**Issue by GermanBluefox** [PArns/ioBroker.innogy-smarthome#75]
# Think about update stable version to 0.4.5
**Version**: stable=**0.3.7** (253 days old) => latest=**0.4.5** (15 days old)
**Installs**: stable=**526** (75.47%), latest=**37** (5.31%), total=**697**
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L854)

**Comment by Apollon77** [comment]
@PArns ready for stable? Maybe better 0.4.7?
