### ISSUE TITLE
Local SmartHome Connection ERROR - v0.4.7

### ISSUE THREAD

**Issue by berthold548463** [PArns/ioBroker.innogy-smarthome#78]
Hello,

I am new to the Livis Local SmartHome Beta and tried to connect my iobroker to my SHC1.0. The adapter brings up a connection to the SHC1.0 via local version and iobroker will find the devices which are connected to my SHC1.0. After that my logfile just shows a ERROR _ECONNREFUSED_ (see below) and the adapter won't work correctly anymore. In addition there is no chance to connect the Livisi Cloud to the adapter *ip-adress*:3000 not found. (No Grafana or something else).

**What have I done so far:**
1. I installed the stable v0.3.7 of the adapter and it is working correctly. Livisi Cloud can be connected.
2. Installed the beta v0.4.7 over the v0.3.7 --> no cloud connection possible and Local SmartHome ERROR
3. Set up a new Raspberry Pi with current Raspbian and newest iobroker etc. --> v0.3.7 is working correctly but v0.4.7 has exactly the same problem.

**My logfile:**
innogy-smarthome.0 | 2022-05-24 19:11:26.415 | error | STACK:Error: connect ECONNREFUSED 192.168.1.13:9090    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
innogy-smarthome.0 | 2022-05-24 19:11:26.413 | error | GOT AN ERROR:{"errno":-111,"code":"ECONNREFUSED","syscall":"connect","address":"192.168.1.13","port":9090}
innogy-smarthome.0 | 2022-05-24 19:11:25.327 | info | Initialization sequence completed: found 30 devices
innogy-smarthome.0 | 2022-05-24 19:11:21.589 | info | Trying to use local smarthome connection!
innogy-smarthome.0 | 2022-05-24 19:11:21.534 | info | starting.  Version 0.4.7 (non-npm: PArns/ioBroker.innogy-smarthome) in  /opt/iobroker/node_modules/iobroker.innogy-smarthome, node: v14.19.3,  js-controller: 4.0.23

![grafik](https://user-images.githubusercontent.com/87242440/170094009-1955916e-1348-46dd-88b7-08a43c2f0e59.png)

 - Adapter version: v0.4.7
 - JS-Controller version: 4.0.23
 - Node version: v14.19.3
 - Operating system: Raspbian GNU/Linux 11 (bullseye)

**Comment by AHahne64** [comment]
Hi everyone,

same Probleme by me.

Thank you for your work.
I use the system only for my smoke detectors.
The rest of my system I sell on Ebay.
I hope it is possible to fix the problem.

One Problem is I think the port settings.
I enlarge the IP nwith the right port :8080 after this I have problems in the log file.
but the adapter is yellow and not green.

Adapter version: v0.4.7
JS-Controller version: 4.0.23
Node version: v16.17.1
NPM Version: 8.19.2
Admin: 6.2.22
Operating system: Debian Linux 11 (bullseye) / LXC Proxmox

Greatings from Arnsberg

Andreas

**Comment by GreatSUN** [comment]
Hey guys...
I am using Innogy Smart Home Central 2 and for me it works as a charm:
with my node.js is still v16.14.2 as of now.
Adapter Versions:
admin 6.2.23
innogy 0.4.7
js 6.1.4

The only thing I see from time to time is that the innogy adapter runs stale in not connected and has to be restarted

**Comment by Apollon77** [comment]
If you can get a debug log  of such a situation this wopuld be helpful I guess

**Comment by Apollon77** [comment]
ECONNREFUSED 192.168.1.13:9090 means that the device with this IP (maybe the innogy device?) refused the connection. Does that log then comes once in the Log or many times? It shlukd try a reconnect, maybe this do not work?

**Comment by Apollon77** [comment]
Duplicate #95
