### ISSUE TITLE
Nach Websocket Update - RangeError

### ISSUE THREAD

**Issue by JBSullivan** [PArns/ioBroker.innogy-smarthome#80]
Nach dem letzten ioB socket.io Update auf  Version 6.1.7 spuckt der Adapter die folgende Fehlermeldung nach einem Admin (6.0.8) Neustart aus.

`<html>
<body>

innogy-smarthome.0 | 2022-06-22 11:56:50.326 | error | STACK:RangeError: Invalid WebSocket frame: invalid status code 0 at Receiver.controlMessage (C:\iobroker\GLT\node_modules\innogy-smarthome-lib\node_modules\ws\lib\receiver.js:449:18) at Receiver.getData (C:\iobroker\GLT\node_modules\innogy-smarthome-lib\node_modules\ws\lib\receiver.js:335:42) at Receiver.startLoop (C:\iobroker\GLT\node_modules\innogy-smarthome-lib\node_modules\ws\lib\receiver.js:138:22) at Receiver._write (C:\iobroker\GLT\node_modules\innogy-smarthome-lib\node_modules\ws\lib\receiver.js:74:10) at writeOrBuffer (internal/streams/writable.js:358:12) at Receiver.Writable.write (internal/streams/writable.js:303:10) at Socket.socketOnData (C:\iobroker\GLT\node_modules\innogy-smarthome-lib\node_modules\ws\lib\websocket.js:864:35) at Socket.emit (events.js:315:20) at addChunk (internal/streams/readable.js:309:12) at readableAddChunk (internal/streams/readable.js:284:9) at Socket.Readable.push (internal/streams/readable.js:223:10) at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
-- | -- | -- | --
innogy-smarthome.0 | 2022-06-22 11:56:50.326 | error | GOT AN ERROR:{}

</body>
</html>`

**Comment by Apollon77** [comment]
Also das hat definitiv nichts mit einem socketip update zu tun. In dem Fall eine ungültige Nachricht vom innogy System er Websocket an ... Komplett verschiedene paar Schuhe

**Comment by JBSullivan** [comment]
Seite heute mit der neuen Admin Version 6.1.4 ist die Fehlermeldung nach dem Admin Neustart nicht mehr vorhanden. Also war es wohl mehr ein Admin Problem ..... oder?

Wie gesagt, bei MIR tritt die Meldung nun nicht mehr auf.

**Comment by Apollon77** [comment]
Na dann ist ja ok ... ich glaubs immer noch nicht :-)) aber wichtig ist das es wieder tut
