### ISSUE TITLE
Stack Range Error

### ISSUE THREAD

**Issue by JBSullivan** [PArns/ioBroker.innogy-smarthome#81]
Vermutlich verursacht durch eines der letzten WebSocket (2.1.3) Updates. Auswirkung auf das laufende System (Zentrale 2.0 - local SmartHome) sind  z.Zt. nicht erkennbar.

Innogy Adapter 0.4.7
Admin 6.2.14
Nodejs 14.16.0
npm 6.14.11

`<html>
<body>

innogy-smarthome.0 | 9956 | 2022-08-09 06:28:35.153 | error | STACK:RangeError: Invalid WebSocket frame: invalid status code 0 at Receiver.controlMessage (C:\iobroker\GLT\node_modules\innogy-smarthome-lib\node_modules\ws\lib\receiver.js:449:18) at Receiver.getData (C:\iobroker\GLT\node_modules\innogy-smarthome-lib\node_modules\ws\lib\receiver.js:335:42) at Receiver.startLoop (C:\iobroker\GLT\node_modules\innogy-smarthome-lib\node_modules\ws\lib\receiver.js:138:22) at Receiver._write (C:\iobroker\GLT\node_modules\innogy-smarthome-lib\node_modules\ws\lib\receiver.js:74:10) at writeOrBuffer (internal/streams/writable.js:358:12) at Receiver.Writable.write (internal/streams/writable.js:303:10) at Socket.socketOnData (C:\iobroker\GLT\node_modules\innogy-smarthome-lib\node_modules\ws\lib\websocket.js:864:35) at Socket.emit (events.js:315:20) at addChunk (internal/streams/readable.js:309:12) at readableAddChunk (internal/streams/readable.js:284:9) at Socket.Readable.push (internal/streams/readable.js:223:10) at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
-- | -- | -- | -- | --
innogy-smarthome.0 | 9956 | 2022-08-09 06:28:35.153 | error | GOT AN ERROR:{}

</body>
</html>`

**Comment by Apollon77** [comment]
solved in 1.0.0 https://forum.iobroker.net/topic/61351/livisi-innogy-smarthome-adapter-1-0-0-breaking
