### ISSUE TITLE
Battery Status/Messages

### ISSUE THREAD

**Issue by JBSullivan** [PArns/ioBroker.innogy-smarthome#83]
Es bestehen offensichtlich gute Aussichten, das vor der Einstellung des Innogy Systems, die dortigen Entwickler den ioBroker Adapter hinsichtlich der "Batterie schwach" Meldung unterstützen können.

Dazu sollte @PArns bitte Kontakt mit dem Innogy/Livisi Entwickler Team aufnehmen - siehe hier -> 

https://community.livisi.de/forum/thread/4507-probleme-der-klassische-zentrale-und-iobroker/?postID=38315#post38315

VIELEN DANK

**Comment by Apollon77** [comment]
Details see https://community.livisi.de/forum/thread/4797-batterylow-event-details/?postID=39876#post39876 (link just for me)

**Comment by Apollon77** [comment]
@JBSullivan Ich weiss das ich Dein Problem gerade vergrössere ... GitHub version sollte isReachable und lowBattery Support haben .... :-)

**Comment by JBSullivan** [comment]
Das ist egal, ich nehme mir dann irgend wann mal die Zeit und schreibe auf dem Produktiv System alle DPs um. Aktuell gucke ich mir nur die DP`s auf dem Testsystem am. Du hast hier in 7 Tagen mehr gerade gezogen als in den letzten 4 Jahren an dem Adapter gemacht wurde. 

VIELEN HERZLICHEN DANK DAFÜR !!!

**Comment by PArns** [comment]
Sorry, das es Menschen gibt, die auch noch ein Leben haben und für die Entwicklung keinen müden Cent bekommen!

**Comment by Apollon77** [comment]
Am Ende geht es immer um Zeit, Prioritäten und Unterstützung. Ich bin sehr froh das @PArns mir hier das Vertrauen gegeben hat "in seinem Repository" und damit "in seinem Namen" zu unterstützen. Danke auch dafür.

Ich kann ebenfalls ein Lied davon singen wie es ist wenn es weniger unterstützende Entwickler gibt als es sinnvoll wäre. Aber gemeinsam bekommen wir das alles hin.

**Comment by Apollon77** [comment]
https://forum.iobroker.net/topic/61351/livisi-innogy-smarthome-adapter-1-0-0-breaking

**Comment by JBSullivan** [comment]
@PArns  Ich wollte dir in keinem Fall zu Nahe treten. Ohne dein früheres Engagement würde es diesen Adapter gar nicht geben und viele User hätten bestimmt dem Innogy / Livisi System schon längst den Rücken gekehrt. Ich kann auch vollkommen verstehen, wenn man keine Zeit oder auch keine Lust mehr hat an so einem Projekt für LAU weiter zu arbeiten -  dann sollte man das aber irgendwo auch so kommunizieren.

Hier sind ja immer wieder Issues aufgemacht worden, wo es leider gar keine Reaktion drauf gab. Da weiß man als Anwender auch nicht, geht es nun weiter oder ist Schluss mit dem Adapter. Da hängt ja unter Umständen auch ein gewaltiger Finanzieller Aspekt dran, wenn man die gesamte Hardware raus schmeißen muss oder will, weil man denkt, wenn Livisi abschaltet und der Adapter Entwickler auch nichts mehr macht, ist das Projekt wohl Tod.

Nun kam hier aber noch erschwerend hinzu, das Livisi seinen Cloud Zugang in Q1-2023 dicht machen wird.  Auch hier war wieder die Entscheidende Frage, geht es LOKAL mit dem System weiter oder ist dann auch damit irgend wann Schluss, weil der Adapter bei auf auftretenden Fehler nicht mehr supported wird.

Darum war ich sehr froh, das @Apollon77 sich die letzten Tage hier echt stark reingehängt hat und viele der alten Issues abarbeiten konnte und sogar noch ein paar neue Features hinzu gefügt hat.

Das soll aber nicht ein Stück den DANK an dich und deine zuvor geleistete Arbeit schmälern - nur hätte ich persönlich mir eine etwas offenere Kommunikation zum "wie geht es weiter" gewünscht.

Nun scheint der Adapter aber erstmal auf einem sehr gute Weg zu sein, das man die Hardware wird noch lange weiter nutzen wird können. Ich denke sogar, das nach dem Q1-2023 der gebraucht Teile Markt mit vielen Innogy / Livisi Produkten überschwemmt wird, da die Leute die nur via Smartphone und  der Cloud gearbeitet haben, ihre Komponenten  abstoßen werden.

Durch den Adapter kann nun zumindest die ioBroker und auch die openhab Gemeinde den gebraucht Geräten einen Second Life Circle verschaffen.

Also auch an dich hier nochmal VIELEN DANK FÜR VORAUS GEGANGENE ARBEIT AN DEM ADAPTER !!!
