### ISSUE TITLE
Zweirichtungszähler 

### ISSUE THREAD

**Issue by ManiacKill** [PArns/ioBroker.innogy-smarthome#85]
Leider bekomme ich an meinem Zweirichtungszähler unter IO Broker nur daten von der Einspeisung. Mir fehlen da alle daten von Bezügen der Energie.

![image](https://user-images.githubusercontent.com/11009572/195899207-dffdae55-f771-4162-a9ca-e256d1c5068f.png)

Vieleicht hilft das hier vom OpenHab

https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.livisismarthome/src/main/java/org/openhab/binding/livisismarthome/internal/handler/LivisiDeviceHandler.java

**Comment by ManiacKill** [comment]
Bitte um Hilfe wegen dem Problem

**Comment by ManiacKill** [comment]
Ist der Adapter tot ? Wird er nicht mehr gefelgt ?

**Comment by Apollon77** [comment]
Also wenn der Adapter noch läuft bei Dir ist er denke ich nicht Tod. Gepflegt wird er bestimmt wenn der Entwickler Zeit hat. 

Stell doch mal ein Debug Log ein,vllt sieht man die Daten ja recht einfach

**Comment by ManiacKill** [comment]
`<html>
<body>


innogy-smarthome.0 | 2022-11-12 09:54:44.086 | debug | OPEN
-- | -- | -- | --
innogy-smarthome.0 | 2022-11-12 09:54:42.899 | warn | setObject Hauswirtschaftsraum.Pool-Pumpe.OnOff (type=state) property common.role missing!
innogy-smarthome.0 | 2022-11-12 09:54:42.898 | warn | Unknown state (please report to dev):onOff {"name":"onOff","value":false,"lastchanged":"2022-11-12T08:53:33.202Z"}
innogy-smarthome.0 | 2022-11-12 09:54:42.897 | warn | setObject Hauswirtschaftsraum.Wärmepumpe.PowerConsumptionWatt (type=state) property common.role missing!
innogy-smarthome.0 | 2022-11-12 09:54:42.896 | warn | Unknown state (please report to dev):powerConsumptionWatt {"name":"powerConsumptionWatt","value":10,"lastchanged":"2022-11-12T08:53:40.916Z"}
innogy-smarthome.0 | 2022-11-12 09:54:42.895 | warn | setObject Hauswirtschaftsraum.Wärmepumpe.EnergyConsumptionDayKWh (type=state) property common.role missing!
innogy-smarthome.0 | 2022-11-12 09:54:42.894 | warn | Unknown state (please report to dev):energyConsumptionDayKWh {"name":"energyConsumptionDayKWh","value":8.963,"lastchanged":"2022-11-12T08:03:36.553Z"}
innogy-smarthome.0 | 2022-11-12 09:54:42.893 | warn | setObject Hauswirtschaftsraum.Wärmepumpe.EnergyConsumptionDayEuro (type=state) property common.role missing!
innogy-smarthome.0 | 2022-11-12 09:54:42.892 | warn | Unknown state (please report to dev):energyConsumptionDayEuro {"name":"energyConsumptionDayEuro","value":1.537,"lastchanged":"2022-11-12T08:03:36.553Z"}
innogy-smarthome.0 | 2022-11-12 09:54:42.891 | warn | setObject Hauswirtschaftsraum.Wärmepumpe.EnergyConsumptionMonthEuro (type=state) property common.role missing!
innogy-smarthome.0 | 2022-11-12 09:54:42.890 | warn | Unknown state (please report to dev):energyConsumptionMonthEuro {"name":"energyConsumptionMonthEuro","value":21.198,"lastchanged":"2022-11-12T08:03:36.553Z"}
innogy-smarthome.0 | 2022-11-12 09:54:42.889 | warn | setObject Hauswirtschaftsraum.Wärmepumpe.AbsoluteEnergyConsumption (type=state) property common.role missing!
innogy-smarthome.0 | 2022-11-12 09:54:42.888 | warn | Unknown state (please report to dev):absoluteEnergyConsumption {"name":"absoluteEnergyConsumption","value":12204.222,"lastchanged":"2022-11-12T08:03:36.553Z"}
innogy-smarthome.0 | 2022-11-12 09:54:42.887 | warn | setObject Hauswirtschaftsraum.Wärmepumpe.EnergyConsumptionMonthKWh (type=state) property common.role missing!
innogy-smarthome.0 | 2022-11-12 09:54:42.885 | warn | Unknown state (please report to dev):energyConsumptionMonthKWh {"name":"energyConsumptionMonthKWh","value":123.604,"lastchanged":"2022-11-12T08:03:36.553Z"}
innogy-smarthome.0 | 2022-11-12 09:54:42.862 | info | Initialization sequence completed: found 13 devices
innogy-smarthome.0 | 2022-11-12 09:54:37.667 | info | starting. Version 0.3.7 in /opt/iobroker/node_modules/iobroker.innogy-smarthome, node: v16.18.0, js-controller: 4.0.23
innogy-smarthome.0 | 2022-11-12 09:54:36.895 | debug | States connected to redis: 192.168.2.220:9000
innogy-smarthome.0 | 2022-11-12 09:54:36.498 | debug | States create User PubSub Client
innogy-smarthome.0 | 2022-11-12 09:54:36.491 | debug | States create System PubSub Client
innogy-smarthome.0 | 2022-11-12 09:54:36.313 | debug | Redis States: Use Redis connection: 192.168.2.220:9000
innogy-smarthome.0 | 2022-11-12 09:54:36.197 | debug | Objects connected to redis: 192.168.2.220:9001
innogy-smarthome.0 | 2022-11-12 09:54:36.179 | debug | Objects client initialize lua scripts
innogy-smarthome.0 | 2022-11-12 09:54:35.873 | debug | Objects create User PubSub Client
innogy-smarthome.0 | 2022-11-12 09:54:35.870 | debug | Objects create System PubSub Client
innogy-smarthome.0 | 2022-11-12 09:54:35.865 | debug | Objects client ready ... initialize now
innogy-smarthome.0 | 2022-11-12 09:54:34.404 | debug | Redis Objects: Use Redis connection: 192.168.2.220:9001


</body>
</html>`

**Comment by ManiacKill** [comment]
Konnte sich das Problem mal jemand anschauen, bekomme es einfach nicht hin noch die fehlenden Daten auszulesen !

**Comment by Apollon77** [comment]
Geduld bitte ....

**Comment by Apollon77** [comment]
Please try GitHub versio and give feedback
