### ISSUE TITLE
Probleme mit WebSocket

### ISSUE THREAD

**Issue by FranticMan** [PArns/ioBroker.innogy-smarthome#89]
Aktuell wird etwa jede Stunde ein Fehler vom Adapter geworfen.
Vermutlich ist der Version des Apapters (0.4.7) nicht mehr mit der aktuellen Version von socket.io (4.2.0) bzw. Node.js (v16.18.1) kompatibel:

`STACK:RangeError: Invalid WebSocket frame: invalid status code 0 at Receiver.controlMessage (/opt/iobroker/node_modules/innogy-smarthome-lib/node_modules/ws/lib/receiver.js:449:18) at Receiver.getData (/opt/iobroker/node_modules/innogy-smarthome-lib/node_modules/ws/lib/receiver.js:335:42) at Receiver.startLoop (/opt/iobroker/node_modules/innogy-smarthome-lib/node_modules/ws/lib/receiver.js:138:22) at Receiver._write (/opt/iobroker/node_modules/innogy-smarthome-lib/node_modules/ws/lib/receiver.js:74:10) at writeOrBuffer (node:internal/streams/writable:391:12) at _write (node:internal/streams/writable:332:10) at Receiver.Writable.write (node:internal/streams/writable:336:10) at Socket.socketOnData (/opt/iobroker/node_modules/innogy-smarthome-lib/node_modules/ws/lib/websocket.js:864:35) at Socket.emit (node:events:513:28) at addChunk (node:internal/streams/readable:315:12) at readableAddChunk (node:internal/streams/readable:289:9) at Socket.Readable.push (node:internal/streams/readable:228:10) at TCP.onStreamRead (node:internal/stream_base_commons:190:23)`

**Comment by Apollon77** [comment]
Was hat das mit dem socketio Adater zu tun? Der Fehler sagt das scheinbar  der WS Server (innogy?) ein fehlerhaftes Websocket Frame gesendet hat.

Hier gibt es keine ünerschneidungenb mit socket.io oder sowas und auch node.js sollte egal sein

**Comment by Apollon77** [comment]
Ok, Der Fehler cheint wohl von einem Falschen Kommando zu kommen und sorgt dann für einen reconnect ... Ist das schlimm?

**Comment by Apollon77** [comment]
https://forum.iobroker.net/topic/61351/livisi-innogy-smarthome-adapter-1-0-0-breaking
