### ISSUE TITLE
Authentification Problem

### ISSUE THREAD

**Issue by eXplOiD1** [PArns/ioBroker.innogy-smarthome#9]
Hello i got an Timeout error every time i try to Authentificat my innogy.

hallo ich bekomme einen timeout jedes mal wenn ich versuche innogy zu Authorisieren.

i hope you can help me

**Comment by PArns** [comment]
Hi, ich gehe mal davon aus, das du das Problem gelöst hast!? Was war die Ursache?

**Comment by eXplOiD1** [comment]
Nach den 20igsten versuch hats dann irgendwann mal geklappt seit dem läufts
