### ISSUE TITLE
Install log von der GitHub Installation ! 

### ISSUE THREAD

**Issue by ManiacKill** [PArns/ioBroker.innogy-smarthome#92]
$ iobroker url https://github.com/PArns/ioBroker.innogy-smarthome.git --host Slave --debug

install PArns/ioBroker.innogy-smarthome#793694e01de5b565661a4c23db2d5d7d62442c00

NPM version: 8.19.2

Installing PArns/ioBroker.innogy-smarthome#793694e01de5b565661a4c23db2d5d7d62442c00... (System call)

up to date in 16s113 packages are looking for funding run `npm fund` for details

upload [1] innogy-smarthome.admin /opt/iobroker/node_modules/iobroker.innogy-smarthome/admin/index.html index.html text/html

upload [0] innogy-smarthome.admin /opt/iobroker/node_modules/iobroker.innogy-smarthome/admin/innogy-smarthome.png innogy-smarthome.png image/png

Process exited with code 0

**Comment by Apollon77** [comment]
This seems like a valid install frm github ... all good
