### ISSUE TITLE
Log von der Installation 0.47 vom GitHub 

### ISSUE THREAD

**Issue by ManiacKill** [PArns/ioBroker.innogy-smarthome#93]
`<html>
<body>

innogy-smarthome.0 | 2022-12-08 05:57:08.296 | warn | You do not have mobile access for the logged in Innogy account! Please purchase mobile access or move ioBroker to the same subnet as the SHC
-- | -- | -- | --
innogy-smarthome.0 | 2022-12-08 05:57:08.026 | warn | You do not have mobile access for the logged in Innogy account! Please purchase mobile access or move ioBroker to the same subnet as the SHC
innogy-smarthome.0 | 2022-12-08 05:57:07.357 | info | Trying to use local smarthome connection!
innogy-smarthome.0 | 2022-12-08 05:57:07.287 | info | starting. Version 0.4.7 (non-npm: PArns/ioBroker.innogy-smarthome#775df96bc0624193bb69c477b4834ba16814e476) in /opt/iobroker/node_modules/iobroker.innogy-smarthome, node: v16.18.0, js-controller: 4.0.23
innogy-smarthome.0 | 2022-12-08 05:57:05.371 | debug | States connected to redis: 192.168.2.220:9000
innogy-smarthome.0 | 2022-12-08 05:57:05.131 | debug | States create User PubSub Client
innogy-smarthome.0 | 2022-12-08 05:57:05.126 | debug | States create System PubSub Client
innogy-smarthome.0 | 2022-12-08 05:57:05.048 | debug | Redis States: Use Redis connection: 192.168.2.220:9000
innogy-smarthome.0 | 2022-12-08 05:57:04.929 | debug | Objects connected to redis: 192.168.2.220:9001
innogy-smarthome.0 | 2022-12-08 05:57:04.915 | debug | Objects client initialize lua scripts
innogy-smarthome.0 | 2022-12-08 05:57:04.578 | debug | Objects create User PubSub Client
innogy-smarthome.0 | 2022-12-08 05:57:04.575 | debug | Objects create System PubSub Client
innogy-smarthome.0 | 2022-12-08 05:57:04.516 | debug | Objects client ready ... initialize now
innogy-smarthome.0 | 2022-12-08 05:57:02.958 | debug | Redis Objects: Use Redis connection: 192.168.2.220:9001
innogy-smarthome.0 | 2022-12-08 05:56:56.565 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
innogy-smarthome.0 | 2022-12-08 05:56:56.562 | info | terminating
innogy-smarthome.0 | 2022-12-08 05:56:56.560 | info | cleaned everything up...
innogy-smarthome.0 | 2022-12-08 05:56:56.554 | error | Converting circular structure to JSON --> starting at object with constructor 'SmartHome' \| property '_parser' -> object with constructor 'ShTypeParser' --- property '_smartHome' closes the circle
innogy-smarthome.0 | 2022-12-08 05:56:56.553 | error | TypeError: Converting circular structure to JSON --> starting at object with constructor 'SmartHome' \| property '_parser' -> object with constructor 'ShTypeParser' --- property '_smartHome' closes the circle at JSON.stringify (<anonymous>) at updateDevice (/opt/iobroker/node_modules/iobroker.innogy-smarthome/main.js:251:68) at /opt/iobroker/node_modules/iobroker.innogy-smarthome/main.js:169:17 at Array.forEach (<anonymous>) at SmartHome.<anonymous> (/opt/iobroker/node_modules/iobroker.innogy-smarthome/main.js:168:30) at SmartHome.emit (node:events:513:28) at /opt/iobroker/node_modules/innogy-smarthome-lib/lib/smarthome/index.js:101:26From previous event: at /opt/iobroker/node_modules/innogy-smarthome-lib/lib/smarthome/index.js:96:39 at processImmediate (node:internal/timers:466:21)From previous event: at /opt/iobroker/node_modules/innogy-smarthome-lib/lib/smarthome/index.js:95:45From previous event: at /opt/iobroker/node_modules/innogy-smarthome-lib/lib/smarthome/index.js:94:35From previous event: at SmartHome.init (/opt/iobroker/node_modules/innogy-smarthome-lib/lib/smarthome/index.js:93:29) at initSmartHome (/opt/iobroker/node_modules/iobroker.innogy-smarthome/main.js:225:15) at Adapter.onMessage (/opt/iobroker/node_modules/iobroker.innogy-smarthome/main.js:37:17) at Adapter.emit (node:events:513:28) at change (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5301:34) at Immediate.<anonymous> (/opt/iobroker/node_modules/@iobroker/db-states-redis/lib/states/statesInRedisClient.js:322:37) at processImmediate (node:internal/timers:466:21)
innogy-smarthome.0 | 2022-12-08 05:56:56.552 | error | unhandled promise rejection: Converting circular structure to JSON --> starting at object with constructor 'SmartHome' \| property '_parser' -> object with constructor 'ShTypeParser' --- property '_smartHome' closes the circle
innogy-smarthome.0 | 2022-12-08 05:56:56.550 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
innogy-smarthome.0 | 2022-12-08 05:56:56.538 | info | Initialization sequence completed: found 13 devices
innogy-smarthome.0 | 2022-12-08 05:55:41.930 | warn | You do not have mobile access for the logged in Innogy account! Please purchase mobile access or move ioBroker to the same subnet as the SHC
innogy-smarthome.0 | 2022-12-08 05:55:41.682 | warn | You do not have mobile access for the logged in Innogy account! Please purchase mobile access or move ioBroker to the same subnet as the SHC
innogy-smarthome.0 | 2022-12-08 05:55:41.449 | info | Trying to use local smarthome connection!
innogy-smarthome.0 | 2022-12-08 05:55:41.355 | info | starting. Version 0.4.7 (non-npm: PArns/ioBroker.innogy-smarthome#775df96bc0624193bb69c477b4834ba16814e476) in /opt/iobroker/node_modules/iobroker.innogy-smarthome, node: v16.18.0, js-controller: 4.0.23
innogy-smarthome.0 | 2022-12-08 05:55:40.113 | debug | States connected to redis: 192.168.2.220:9000
innogy-smarthome.0 | 2022-12-08 05:55:39.860 | debug | States create User PubSub Client
innogy-smarthome.0 | 2022-12-08 05:55:39.854 | debug | States create System PubSub Client
innogy-smarthome.0 | 2022-12-08 05:55:39.559 | debug | Redis States: Use Redis connection: 192.168.2.220:9000
innogy-smarthome.0 | 2022-12-08 05:55:39.408 | debug | Objects connected to redis: 192.168.2.220:9001
innogy-smarthome.0 | 2022-12-08 05:55:39.386 | debug | Objects client initialize lua scripts
innogy-smarthome.0 | 2022-12-08 05:55:39.030 | debug | Objects create User PubSub Client
innogy-smarthome.0 | 2022-12-08 05:55:39.026 | debug | Objects create System PubSub Client
innogy-smarthome.0 | 2022-12-08 05:55:38.951 | debug | Objects client ready ... initialize now
innogy-smarthome.0 | 2022-12-08 05:55:37.075 | debug | Redis Objects: Use Redis connection: 192.168.2.220:9001

</body>
</html>`

**Comment by ManiacKill** [comment]
Ich hab die kpl Innogy-smarthome instanz gelöscht und die von GitHub installiert. Leider funktioniert der  Adapter jetzt Gar nicht mehr !

**Comment by Apollon77** [comment]
Please retry from gitHub
