### ISSUE TITLE
4 "Unkown States" in Version 1.0.0

### ISSUE THREAD

**Issue by j64bit** [PArns/ioBroker.innogy-smarthome#97]
Hi 
I am using version 1.0.0 - many thanks for the update. Starts much more cleanly than the previous.
I'm also using the local SHC.

There are four unkown state message, which I'm asked to report. Happy to do so:

```
Unknown state (please report to dev):ssid {"name":"ssid","value":"myWLAN","lastchanged":"1970-01-01T00:00:00.000Z"}
Unknown state (please report to dev):signalStrength {"name":"signalStrength","value":-60,"lastchanged":"2022-12-28T10:45:16.417Z"}
Unknown state (please report to dev):lightState {"name":"lightState","value":false,"lastchanged":"2022-12-28T08:12:47.487Z"}
Unknown state (please report to dev):doorState {"name":"doorState","value":"closed","lastchanged":"2022-12-28T08:11:48.209Z"}
```

Hope this helps and if wanted, i'm happy to provide further information.
Please keep up the great work - the adapter is one of the most important ones to me.

Greetings
Jorg

**Comment by Apollon77** [comment]
Will be added in next version

**Comment by Apollon77** [comment]
Fixed in 1.1.0

**Comment by j64bit** [comment]
That was quick! and I can confirm these messages are gone now - perfect.
Many thanks again

**Comment by j64bit** [comment]
FYI: these all seem to be related to the NOVOFERM garage door in my case

**Comment by Apollon77** [comment]
Thanks for the confirmation
