### ISSUE TITLE
Falsche Ladestrom Einheit bei ALKO Mäher

### ISSUE THREAD

**Issue by JBSullivan** [PArns/ioBroker.innogy-smarthome#98]
Vielleicht könnt ihr beim nächsten Update die Einheit des Ladestrom beim ALKO Mäher noch ändern. Korrekter Weise muss das mA und nicht W sein. Kann man zwar selber machen, aber beim nächsten neu erzeugen des Objekt Baum steht da wieder W(att) drin.

![image](https://user-images.githubusercontent.com/44617472/210597130-1b3541a9-948a-49ad-9aa6-d5cffe3f3e29.png)

**Comment by Apollon77** [comment]
Na klar ... GitHub fixed ... kommt in nächsten release
