### ISSUE TITLE
Rauchmelder Auslösung - DP Frage

### ISSUE THREAD

**Issue by JBSullivan** [PArns/ioBroker.innogy-smarthome#99]
Kurze Frage zu den beiden Datenpunkten der WSD2 Rauchmelder.

![image](https://user-images.githubusercontent.com/44617472/210604322-a04c0930-6273-4bc0-8481-9c8fea0c256f.png)

Der Datenpunkt `innogy-smarthome.0.-----WSD2.OnState` löst alle im Haus befindlichen Rauchmelder aus, wenn man von False auf True steuert.  

Somit würde ich erwarten, das der DP `innogy-smarthome.0.-----.WSD2.IsSmokeAlarm` nur den gewählten einzelnen Rauchmelder auslöst. Hier passiert aber bei der Änderung von True auf False gar nichts. Oder ist das als Signalisierung gedacht, damit sehen kann in welchem Raum der Rauchmelder ausgelöst hat?

Was sagt die Livisi / Innogy API Doku dazu?

**Comment by Apollon77** [comment]
Da ich da keine Details habe kann ich da nicht sagen ... Bitte im Livisi Forum fragen. Ich tippe darauf das ein Is* State nur Lesend für einen Zustand ist
